SET LINESIZE 220
SET PAGESIZE 50
SET TRIMOUT ON
SET TRIMSPOOL ON

COLUMN REPORT_ID     FORMAT 999999999
COLUMN VENDOR_ID     FORMAT 999999999
COLUMN VENDOR_NAME   FORMAT A25
COLUMN PRODUCT_ID    FORMAT 999999999
COLUMN PRODUCT_NAME  FORMAT A30
COLUMN CATEGORY      FORMAT A20
COLUMN LICENSE_ID    FORMAT 999999999
COLUMN UNIT_PRICE    FORMAT 9999990.00
COLUMN TOTAL_SEATS   FORMAT 999999999
COLUMN LICENSE_COST  FORMAT 9999990.00
--1
CREATE TABLE Report
(
    id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_xml XMLTYPE NOT NULL
);
/

-- 2. Процедура генерации XML

CREATE OR REPLACE PROCEDURE sp_GenerateLicenseXml
(
    p_report_xml OUT XMLTYPE
)
AS
BEGIN
    SELECT XMLELEMENT(
               "LicenseReport",
               XMLATTRIBUTES(
                   TO_CHAR(SYSTIMESTAMP, 'YYYY-MM-DD"T"HH24:MI:SS.FF3') AS "generatedAt"
    ),
    (
    SELECT XMLELEMENT(
        "Total",
        XMLELEMENT("LicensesCount", COUNT(*)),
        XMLELEMENT("TotalSeats", SUM(l.Total_Seats)),
        XMLELEMENT("TotalCost", SUM(l.Unit_Price * l.Total_Seats))
        )
    FROM Licenses l
    ),

    XMLELEMENT(
        "Licenses",
            (
                SELECT XMLAGG(
                    XMLELEMENT(
                        "LicenseInfo",
                                      XMLATTRIBUTES(
                                          v.Vendor_ID  AS "vendorId",
                                          v.Name AS "vendorName",
                                          p.Product_ID AS "productId",
                                          p.Name AS "productName",
                                          p.Category AS "category",
                                          l.License_ID AS "licenseId"
                                      ),
                                      XMLELEMENT("UnitPrice", l.Unit_Price),
                                      XMLELEMENT("TotalSeats", l.Total_Seats),
                                      XMLELEMENT("LicenseCost", l.Unit_Price * l.Total_Seats)
                                  )
                                  ORDER BY v.Vendor_ID, p.Product_ID, l.License_ID
                              )
                       FROM Vendors v
                           JOIN Products p ON p.Vendor_ID = v.Vendor_ID
                           JOIN Licenses l ON l.Product_ID = p.Product_ID
                   )
               ),
               XMLELEMENT(
                   "VendorTotals",
                   (
                       SELECT XMLAGG(
                                  XMLELEMENT(
                                      "VendorTotal",
                                      XMLATTRIBUTES(t.vendor_name AS "vendorName"),
                                      XMLELEMENT("LicensesCount", t.licenses_count),
                                      XMLELEMENT("TotalSeats", t.total_seats),
                                      XMLELEMENT("VendorTotalCost", t.vendor_total_cost)
                                  )
                                  ORDER BY t.vendor_name
                              )
                       FROM
                       (
                           SELECT
                               v.Name AS vendor_name,
                               COUNT(l.License_ID) AS licenses_count,
                               SUM(l.Total_Seats) AS total_seats,
                               SUM(l.Unit_Price * l.Total_Seats) AS vendor_total_cost
                           FROM Vendors v
                               JOIN Products p ON p.Vendor_ID = v.Vendor_ID
                               JOIN Licenses l ON l.Product_ID = p.Product_ID
                           GROUP BY v.Name
                       ) t
                   )
               )
           )
    INTO p_report_xml
    FROM dual;
END;
/

-- 3

CREATE OR REPLACE PROCEDURE sp_InsertLicenseReport
AS
    v_xml XMLTYPE;
    v_id  NUMBER;
BEGIN
    sp_GenerateLicenseXml(v_xml);

    INSERT INTO Report(report_xml)
    VALUES (v_xml)
    RETURNING id INTO v_id;

    COMMIT;
END;
/


BEGIN
    sp_InsertLicenseReport;
END;
/

SELECT
    id,
    XMLSERIALIZE(DOCUMENT report_xml AS CLOB INDENT SIZE = 2) AS report_xml_text
FROM Report;
/

-- 4
CREATE INDEX idx_report_xml ON Report(report_xml)
INDEXTYPE IS XDB.XMLINDEX;
/


SELECT *
FROM Report
WHERE XMLEXISTS(
    '/LicenseReport/Licenses/LicenseInfo[@vendorName="Microsoft"]'
    PASSING report_xml
);
/

EXPLAIN PLAN FOR
SELECT *
FROM Report
WHERE XMLEXISTS('/LicenseReport/Licenses/LicenseInfo[@vendorName="Microsoft"]'
    PASSING report_xml
);
/

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY());
/

-- 5.
CREATE OR REPLACE PROCEDURE sp_GetXmlReportByVendorName
(
    p_vendor_name IN NVARCHAR2,
    p_result OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN p_result FOR
        SELECT
            r.id AS report_id,
            x.vendor_id,
            x.vendor_name,
            x.product_id,
            x.product_name,
            x.category,
            x.license_id,
            x.unit_price,
            x.total_seats,
            x.license_cost
        FROM Report r
            CROSS JOIN XMLTABLE(
                '/LicenseReport/Licenses/LicenseInfo[@vendorName=$vendorName]'
                PASSING r.report_xml, p_vendor_name AS "vendorName"
                COLUMNS
                    vendor_id NUMBER PATH '@vendorId',
                    vendor_name NVARCHAR2(255) PATH '@vendorName',
                    product_id NUMBER PATH '@productId',
                    product_name NVARCHAR2(255) PATH '@productName',
                    category NVARCHAR2(100) PATH '@category',
                    license_id NUMBER PATH '@licenseId',
                    unit_price NUMBER(18,2) PATH 'UnitPrice',
                    total_seats NUMBER PATH 'TotalSeats',
                    license_cost NUMBER(18,2) PATH 'LicenseCost'
            ) x;
END;
/


VARIABLE rc REFCURSOR;
BEGIN
    sp_GetXmlReportByVendorName('Microsoft', :rc);
END;
/
PRINT rc;
