delete from products;
select * from products;

-- 1. Добавление столбца Parent_ID с внешним ключом

ALTER TABLE Products ADD Parent_ID NUMBER;

ALTER TABLE Products ADD CONSTRAINT fk_products_parent
    FOREIGN KEY (Parent_ID) REFERENCES Products (Product_ID);

CREATE INDEX idx_products_parent ON Products (Parent_ID);


-- 2. Процедура GetProductHierarchy

CREATE OR REPLACE PROCEDURE GetProductHierarchy (
    p_ParentID IN NUMBER   
)
AS
BEGIN
    FOR rec IN (
        SELECT Product_ID,
               Name,
               Category,
               Parent_ID,
               LEVEL AS Hierarchy_Level,
               SYS_CONNECT_BY_PATH(Name, ' / ') AS Full_Path
        FROM   Products
        START WITH Product_ID = p_ParentID
        CONNECT BY PRIOR Product_ID = Parent_ID
        ORDER SIBLINGS BY Name
    )
    LOOP
        DBMS_OUTPUT.PUT_LINE(
            LPAD(' ', (rec.Hierarchy_Level - 1) * 4) ||
            'ID='       || rec.Product_ID      ||
            ' Name='    || rec.Name            ||
            ' Cat='     || rec.Category        ||
            ' Parent='  || NVL(TO_CHAR(rec.Parent_ID), 'NULL') ||
            ' Level='   || rec.Hierarchy_Level ||
            ' Path='    || rec.Full_Path
        );
    END LOOP;
END;
/


-- 3. Процедура AddProductChild

CREATE OR REPLACE PROCEDURE AddProductChild (
    p_ParentID  IN NUMBER,
    p_Vendor_ID IN NUMBER,
    p_Name      IN VARCHAR2,
    p_Category  IN VARCHAR2,
    p_Version   IN VARCHAR2
)
AS
    v_exists NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO   v_exists
    FROM   Products
    WHERE  Product_ID = p_ParentID;

    IF v_exists = 0 THEN
        RAISE_APPLICATION_ERROR(-20001,
            'Родительский узел с Product_ID=' || p_ParentID || ' не найден');
    END IF;

    INSERT INTO Products (Vendor_ID, Name, Category, Version, Parent_ID)
    VALUES (p_Vendor_ID, p_Name, p_Category, p_Version, p_ParentID);

    COMMIT;
END;
/


-- 4. Процедура MoveProductSubtree

CREATE OR REPLACE PROCEDURE MoveProductSubtree (
    p_NodeID      IN NUMBER,  
    p_NewParentID IN NUMBER   
)
AS
    v_exists    NUMBER;
    v_is_cycle  NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO   v_exists
    FROM   Products
    WHERE  Product_ID = p_NewParentID;

    IF v_exists = 0 THEN
        RAISE_APPLICATION_ERROR(-20002,
            'Новый родитель с Product_ID=' || p_NewParentID || ' не найден');
    END IF;

    SELECT COUNT(*)
    INTO   v_is_cycle
    FROM   Products
    WHERE  Product_ID = p_NewParentID
    START WITH Product_ID = p_NodeID
    CONNECT BY PRIOR Product_ID = Parent_ID;

    IF v_is_cycle > 0 THEN
        RAISE_APPLICATION_ERROR(-20003,
            'Нельзя переместить узел под собственного потомка – образуется цикл');
    END IF;

    UPDATE Products
    SET    Parent_ID = p_NewParentID
    WHERE  Product_ID = p_NodeID;

    COMMIT;
END;
/


-- ДЕМОНСТРАЦИЯ

-- Очистка
DELETE FROM Products;
COMMIT;
ALTER TABLE Products MODIFY Product_ID GENERATED BY DEFAULT AS IDENTITY (START WITH 1);


INSERT INTO Products (Product_ID, Vendor_ID, Name, Category, Version, Parent_ID)
    VALUES (1, 1, 'Software Catalog',     'Root',        '1.0', NULL);   
INSERT INTO Products (Product_ID, Vendor_ID, Name, Category, Version, Parent_ID)
    VALUES (2, 1, 'Office Software',      'Category',    '1.0', 1);     
INSERT INTO Products (Product_ID, Vendor_ID, Name, Category, Version, Parent_ID)
    VALUES (3, 1, 'Development Software', 'Category',    '1.0', 1);     
INSERT INTO Products (Product_ID, Vendor_ID, Name, Category, Version, Parent_ID)
    VALUES (4, 1, 'Word Processor',       'Subcategory', '1.0', 2);       
INSERT INTO Products (Product_ID, Vendor_ID, Name, Category, Version, Parent_ID)
    VALUES (5, 1, 'Spreadsheets',         'Subcategory', '1.0', 2);     
INSERT INTO Products (Product_ID, Vendor_ID, Name, Category, Version, Parent_ID)
    VALUES (6, 1, 'IDE',                  'Subcategory', '1.0', 3);       
INSERT INTO Products (Product_ID, Vendor_ID, Name, Category, Version, Parent_ID)
    VALUES (7, 1, 'Version Control',      'Subcategory', '1.0', 3);      
COMMIT;
ALTER TABLE Products MODIFY Product_ID GENERATED BY DEFAULT AS IDENTITY (START WITH 8);


SELECT Product_ID, Vendor_ID, Name, Category, Version, Parent_ID
FROM   Products
ORDER  BY Product_ID;

-- 2. Тестирование GetProductHierarchy
SET SERVEROUTPUT ON;

EXEC GetProductHierarchy(1);

EXEC GetProductHierarchy(3);


-- 3. Тестирование AddProductChild
BEGIN
    AddProductChild(
        p_ParentID  => 4,      
        p_Vendor_ID => 1,
        p_Name      => 'Advanced Word Plugin',
        p_Category  => 'Addon',
        p_Version   => 'v2'
    );
END;
/

SELECT Product_ID, Name, Category, Parent_ID
FROM   Products
ORDER  BY Product_ID;

EXEC GetProductHierarchy(1);


-- 4. Тестирование MoveProductSubtree
BEGIN

    MoveProductSubtree(
        p_NodeID      => 3,
        p_NewParentID => 2             
    );
END;
/

EXEC GetProductHierarchy(1);

SELECT Product_ID, Name, Category, Parent_ID
FROM   Products
ORDER  BY Product_ID;