events {}

http {
    server {
        listen 20000;

        location /api/Save-JSON {
            proxy_pass http://backend:40000/NGINX-test;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
