events {}

http {

    include       mime.types;

    server {
        listen 20000;

        location /api/Save-JSON {
            proxy_pass http://backend:40000/NGINX-test;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /TDWA02-02/ {
            alias /usr/share/nginx/html/static-react/;
            index index.html;
            try_files $uri $uri/ /index.html;
        }

        location / {
            root /usr/share/nginx/html/static;
            index TDWA02-01.html;
        }


    }

    server {
        listen 20443 ssl;

        ssl_certificate /etc/nginx/ssl/nginx.crt;
        ssl_certificate_key /etc/nginx/ssl/nginx.key;

        location /api/Save-JSON {
            proxy_pass http://backend:40000/NGINX-test;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /TDWA02-02/ {
            alias /usr/share/nginx/html/static-react/;
            index index.html;
            try_files $uri $uri/ /index.html;
        }

        location / {
            root /usr/share/nginx/html/static;
            index TDWA03-01.html;
        }
    }
}

