services:
  webdav:
    image: bytemark/webdav
    container_name: nginx_webdav
    ports:
      - "8080:80"
    environment:
      AUTH_TYPE: Basic
      USERNAME: user1
      PASSWORD: 12345
    volumes:
      - ./data:/var/lib/dav