server {
    listen 80;

    location /webdav/ {
        root /var/www;

        auth_basic "WebDAV";
        auth_basic_user_file /etc/nginx/.htpasswd;

        dav_methods PUT DELETE MKCOL COPY MOVE;
        create_full_put_path on;
        dav_access user:rw group:rw all:rw;

        autoindex on;
    }
}