delete from products;
select * from products;

-- 1. Добавление столбца Parent_ID с внешним ключом

ALTER TABLE Products ADD Parent_ID NUMBER;

ALTER TABLE Products ADD CONSTRAINT fk_products_parent
    FOREIGN KEY (Parent_ID) REFERENCES Products (Product_ID);

-- Индекс для быстрого поиска детей
CREATE INDEX idx_products_parent ON Products (Parent_ID);


-- 2. Процедура GetProductHierarchy

CREATE OR REPLACE PROCEDURE GetProductHierarchy (
    p_ParentID IN NUMBER   -- Product_ID родительского узла
)
AS
BEGIN
    FOR rec IN (
        SELECT Product_ID,
               Name,
               Category,
               Parent_ID,
               LEVEL AS Hierarchy_Level,
               SYS_CONNECT_BY_PATH(Name, ' / ') AS Full_Path
        FROM   Products
        START WITH Product_ID = p_ParentID
        CONNECT BY PRIOR Product_ID = Parent_ID
        ORDER SIBLINGS BY Name
    )
    LOOP
        DBMS_OUTPUT.PUT_LINE(
            LPAD(' ', (rec.Hierarchy_Level - 1) * 4) ||
            'ID='       || rec.Product_ID      ||
            ' Name='    || rec.Name            ||
            ' Cat='     || rec.Category        ||
            ' Parent='  || NVL(TO_CHAR(rec.Parent_ID), 'NULL') ||
            ' Level='   || rec.Hierarchy_Level ||
            ' Path='    || rec.Full_Path
        );
    END LOOP;
END;
/


-- 3. Процедура AddProductChild

CREATE OR REPLACE PROCEDURE AddProductChild (
    p_ParentID  IN NUMBER,
    p_Vendor_ID IN NUMBER,
    p_Name      IN VARCHAR2,
    p_Category  IN VARCHAR2,
    p_Version   IN VARCHAR2
)
AS
    v_exists NUMBER;
BEGIN
    -- Проверяем, что родитель существует
    SELECT COUNT(*)
    INTO   v_exists
    FROM   Products
    WHERE  Product_ID = p_ParentID;

    IF v_exists = 0 THEN
        RAISE_APPLICATION_ERROR(-20001,
            'Родительский узел с Product_ID=' || p_ParentID || ' не найден');
    END IF;

    INSERT INTO Products (Vendor_ID, Name, Category, Version, Parent_ID)
    VALUES (p_Vendor_ID, p_Name, p_Category, p_Version, p_ParentID);

    COMMIT;
END;
/


-- 4. Процедура MoveProductSubtree

CREATE OR REPLACE PROCEDURE MoveProductSubtree (
    p_NodeID      IN NUMBER,   -- Product_ID перемещаемого узла
    p_NewParentID IN NUMBER    -- Product_ID нового родителя
)
AS
    v_exists    NUMBER;
    v_is_cycle  NUMBER;
BEGIN
    -- Проверяем, что новый родитель существует
    SELECT COUNT(*)
    INTO   v_exists
    FROM   Products
    WHERE  Product_ID = p_NewParentID;

    IF v_exists = 0 THEN
        RAISE_APPLICATION_ERROR(-20002,
            'Новый родитель с Product_ID=' || p_NewParentID || ' не найден');
    END IF;

    SELECT COUNT(*)
    INTO   v_is_cycle
    FROM   Products
    WHERE  Product_ID = p_NewParentID
    START WITH Product_ID = p_NodeID
    CONNECT BY PRIOR Product_ID = Parent_ID;

    IF v_is_cycle > 0 THEN
        RAISE_APPLICATION_ERROR(-20003,
            'Нельзя переместить узел под собственного потомка — образуется цикл');
    END IF;

    -- Переносим: достаточно обновить одну строку
    UPDATE Products
    SET    Parent_ID = p_NewParentID
    WHERE  Product_ID = p_NodeID;

    COMMIT;
END;
/


-- ДЕМОНСТРАЦИЯ

-- Очистка
DELETE FROM Products;
COMMIT;

ALTER TABLE Products MODIFY Product_ID GENERATED BY DEFAULT AS IDENTITY (START WITH 1);


-- Вставка демо-данных
INSERT INTO Products (Product_ID, Vendor_ID, Name, Category, Version, Parent_ID)
    VALUES (1, 1, 'Software Catalog',     'Root',        '1.0', NULL);    -- корень
INSERT INTO Products (Product_ID, Vendor_ID, Name, Category, Version, Parent_ID)
    VALUES (2, 1, 'Office Software',      'Category',    '1.0', 1);       -- ребёнок корня
INSERT INTO Products (Product_ID, Vendor_ID, Name, Category, Version, Parent_ID)
    VALUES (3, 1, 'Development Software', 'Category',    '1.0', 1);       -- ребёнок корня
INSERT INTO Products (Product_ID, Vendor_ID, Name, Category, Version, Parent_ID)
    VALUES (4, 1, 'Word Processor',       'Subcategory', '1.0', 2);       -- ребёнок Office
INSERT INTO Products (Product_ID, Vendor_ID, Name, Category, Version, Parent_ID)
    VALUES (5, 1, 'Spreadsheets',         'Subcategory', '1.0', 2);       -- ребёнок Office
INSERT INTO Products (Product_ID, Vendor_ID, Name, Category, Version, Parent_ID)
    VALUES (6, 1, 'IDE',                  'Subcategory', '1.0', 3);       -- ребёнок Dev
INSERT INTO Products (Product_ID, Vendor_ID, Name, Category, Version, Parent_ID)
    VALUES (7, 1, 'Version Control',      'Subcategory', '1.0', 3);       -- ребёнок Dev
COMMIT;

-- Сброс IDENTITY после ручной вставки
ALTER TABLE Products MODIFY Product_ID GENERATED BY DEFAULT AS IDENTITY (START WITH 8);


-- Просмотр всей таблицы
SELECT Product_ID, Vendor_ID, Name, Category, Version, Parent_ID
FROM   Products
ORDER  BY Product_ID;


-- Просмотр иерархии через CONNECT BY (без процедуры, для наглядности)
SELECT Product_ID,
       LPAD(' ', (LEVEL - 1) * 4) || Name AS Tree_View,
       Category,
       Parent_ID,
       LEVEL AS Hierarchy_Level,
       SYS_CONNECT_BY_PATH(Name, ' / ') AS Full_Path
FROM   Products
START WITH Parent_ID IS NULL
CONNECT BY PRIOR Product_ID = Parent_ID
ORDER SIBLINGS BY Name;


-- То же через рекурсивный CTE (альтернатива CONNECT BY)
WITH hierarchy (Product_ID, Name, Category, Parent_ID, Lvl, Full_Path) AS (
    -- Якорь: корневые узлы
    SELECT Product_ID, Name, Category, Parent_ID,
           1 AS Lvl,
           '/ ' || Name AS Full_Path
    FROM   Products
    WHERE  Parent_ID IS NULL

    UNION ALL

    -- Рекурсивный шаг: дети
    SELECT p.Product_ID, p.Name, p.Category, p.Parent_ID,
           h.Lvl + 1,
           h.Full_Path || ' / ' || p.Name
    FROM   Products p
    JOIN   hierarchy h ON p.Parent_ID = h.Product_ID
)
SELECT Product_ID,
       LPAD(' ', (Lvl - 1) * 4) || Name AS Tree_View,
       Category,
       Parent_ID,
       Lvl AS Hierarchy_Level,
       Full_Path
FROM   hierarchy
ORDER  BY Full_Path;


-- 2. Тестирование GetProductHierarchy
SET SERVEROUTPUT ON;

-- Всё дерево от корня (Product_ID = 1)
EXEC GetProductHierarchy(1);

-- Поддерево Development Software (Product_ID = 3)
EXEC GetProductHierarchy(3);


-- 3. Тестирование AddProductChild
BEGIN
    AddProductChild(
        p_ParentID  => 4,          -- под Word Processor
        p_Vendor_ID => 1,
        p_Name      => 'Advanced Word Plugin',
        p_Category  => 'Addon',
        p_Version   => 'v2'
    );
END;
/

SELECT Product_ID, Name, Category, Parent_ID
FROM   Products
ORDER  BY Product_ID;

-- Проверка в дереве
EXEC GetProductHierarchy(1);


-- 4. Тестирование MoveProductSubtree

DECLARE
    v_plugin_id NUMBER;
BEGIN
    SELECT Product_ID
    INTO   v_plugin_id
    FROM   Products
    WHERE  Name = 'Advanced Word Plugin';

    MoveProductSubtree(
        p_NodeID      => v_plugin_id,
        p_NewParentID => 5              -- Spreadsheets
    );
END;
/

EXEC GetProductHierarchy(1);

-- Табличный вид
SELECT Product_ID, Name, Category, Parent_ID
FROM   Products
ORDER  BY Product_ID;