[pytest]
markers =
    smoke: критичные базовые тесты (быстрый прогон)
    regression: полная регрессия
    cart: тесты корзины
    login: тесты авторизации
    e2e: end-to-end сценарии
    cookies: работа с куками
addopts = -v --tb=short --html=report.html --self-contained-html