ALTER SESSION SET CONTAINER = CDB$ROOT;
-- 1. Создание PDB
-- В параметре FILE_NAME_CONVERT первый путь - это где лежит шаблон (SEED), 
-- а второй - куда мы копируем файлы новой базы.
CREATE PLUGGABLE DATABASE license_pdb
  ADMIN USER license_admin IDENTIFIED BY "1234"
  FILE_NAME_CONVERT = (
    '/opt/oracle/oradata/XE/pdbseed/', 
    '/opt/oracle/oradata/XE/license_pdb/'
  );
  
show con_name;
alter data

-- 2. Открытие и сохранение состояния
ALTER SESSION SET CONTAINER = CDB$ROOT;
ALTER PLUGGABLE DATABASE license_pdb OPEN;
ALTER PLUGGABLE DATABASE license_pdb SAVE STATE;

select * from dba_tables;

-- 3. Переход в контекст новой базы
ALTER SESSION SET CONTAINER = license_pdb;

show con_name;

--постоянное табличное пространство
CREATE TABLESPACE LICENSE_DATA
DATAFILE '/opt/oracle/oradata/XE/license_pdb/license_data.dbf'
SIZE 100M
AUTOEXTEND ON;

--временное табличное пространство
CREATE TEMPORARY TABLESPACE LICENSE_TEMP
TEMPFILE '/opt/oracle/oradata/XE/license_pdb/license_temp.dbf'
SIZE 50M
AUTOEXTEND ON;

-- 6. Настройка прав администратора схемы
ALTER USER license_admin DEFAULT TABLESPACE LICENSE_DATA;
ALTER USER license_admin TEMPORARY TABLESPACE LICENSE_TEMP;
GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE PROCEDURE, CREATE TRIGGER TO license_admin;
GRANT DBA TO license_admin;
ALTER USER license_admin QUOTA UNLIMITED ON LICENSE_DATA;
-------------------------------------------------------------------------------

-- 1. Таблица: Vendors (Поставщики)
CREATE TABLE Vendors (
    Vendor_ID   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name        NVARCHAR2(255) NOT NULL,
    Email       NVARCHAR2(255)
);

-- 2. Таблица: Locations (Помещения)
CREATE TABLE Locations (
    Location_ID          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Room_Number          NVARCHAR2(50) NOT NULL,
    Planned_Growth_Seats NUMBER DEFAULT 0
);

-- 3. Таблица: Products (Репозиторий ПО)
CREATE TABLE Products (
    Product_ID  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Vendor_ID   NUMBER NOT NULL,
    Name        NVARCHAR2(255) NOT NULL,
    Category    NVARCHAR2(100) NOT NULL,
    Version     NVARCHAR2(50),
    CONSTRAINT fk_products_vendors FOREIGN KEY (Vendor_ID) REFERENCES Vendors(Vendor_ID)
);

-- 4. Таблица: Licenses (Лицензии)
CREATE TABLE Licenses (
    License_ID       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Product_ID       NUMBER NOT NULL,
    Purchase_Date    DATE NOT NULL,
    Expiration_Date  DATE,
    Unit_Price       NUMBER(18, 2) NOT NULL,
    Total_Seats      NUMBER NOT NULL,
    CONSTRAINT fk_licenses_products FOREIGN KEY (Product_ID) REFERENCES Products(Product_ID)
);

-- 5. Таблица: Devices (Инвентаризация оборудования)
CREATE TABLE Devices (
    Device_ID            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Location_ID          NUMBER NOT NULL,
    Device_Type          NVARCHAR2(50) NOT NULL,
    Purchase_Date        DATE NOT NULL,
    Service_Life_Months  NUMBER NOT NULL,
    Hostname             NVARCHAR2(100),
    CONSTRAINT fk_devices_locations FOREIGN KEY (Location_ID) REFERENCES Locations(Location_ID)
);

-- 6. Таблица: Installations (Учет использования)
CREATE TABLE Installations (
    Install_ID          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Device_ID           NUMBER NOT NULL,
    License_ID          NUMBER NOT NULL,
    Last_Activity_Date  TIMESTAMP,
    Usage_Count         NUMBER DEFAULT 0,
    CONSTRAINT fk_inst_devices FOREIGN KEY (Device_ID) REFERENCES Devices(Device_ID),
    CONSTRAINT fk_inst_licenses FOREIGN KEY (License_ID) REFERENCES Licenses(License_ID)
);

-- 7. Таблица: Requests (Заявки)
CREATE TABLE Requests (
    Request_ID    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Product_ID    NUMBER NOT NULL,
    User_Name     NVARCHAR2(255) NOT NULL,
    User_Email    NVARCHAR2(255),
    Request_Date  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Status        NVARCHAR2(50) DEFAULT 'В ожидании',
    CONSTRAINT fk_requests_products FOREIGN KEY (Product_ID) REFERENCES Products(Product_ID)
);


CREATE OR REPLACE VIEW vw_ProductCostSummary AS
SELECT 
    p.Product_ID,
    p.Name AS ProductName,
    EXTRACT(YEAR FROM l.Purchase_Date) AS Year,
    EXTRACT(MONTH FROM l.Purchase_Date) AS Month,
    SUM(l.Total_Seats) AS TotalQuantity,
    SUM(l.Total_Seats * l.Unit_Price) AS TotalCost
FROM Licenses l
JOIN Products p ON l.Product_ID = p.Product_ID
GROUP BY p.Product_ID, p.Name, EXTRACT(YEAR FROM l.Purchase_Date), EXTRACT(MONTH FROM l.Purchase_Date);
/

CREATE OR REPLACE VIEW vw_VendorSpending AS
SELECT 
    v.Vendor_ID,
    v.Name AS VendorName,
    EXTRACT(YEAR FROM l.Purchase_Date) AS Year,
    EXTRACT(MONTH FROM l.Purchase_Date) AS Month,
    SUM(l.Total_Seats * l.Unit_Price) AS TotalSpent
FROM Licenses l
JOIN Products p ON l.Product_ID = p.Product_ID
JOIN Vendors v ON p.Vendor_ID = v.Vendor_ID
WHERE l.Purchase_Date >= ADD_MONTHS(SYSDATE, -6)
GROUP BY v.Vendor_ID, v.Name, EXTRACT(YEAR FROM l.Purchase_Date), EXTRACT(MONTH FROM l.Purchase_Date);
/

CREATE INDEX idx_Licenses_ProductPurchase
ON Licenses(Product_ID, Purchase_Date);

CREATE INDEX idx_Installations_DeviceLicenseDate
ON Installations(Device_ID, License_ID, Last_Activity_Date);


CREATE OR REPLACE PROCEDURE sp_AddVendor(
    p_Name IN VARCHAR2,
    p_Email IN VARCHAR2 DEFAULT NULL
) IS
BEGIN
    INSERT INTO Vendors (Name, Email)
    VALUES (p_Name, p_Email);
END;
/

CREATE OR REPLACE PROCEDURE sp_AddLocation(
    p_Room_Number IN VARCHAR2,
    p_Planned_Growth_Seats IN NUMBER DEFAULT 0
) IS
BEGIN
    INSERT INTO Locations (Room_Number, Planned_Growth_Seats)
    VALUES (p_Room_Number, p_Planned_Growth_Seats);
END;
/

CREATE OR REPLACE PROCEDURE sp_AddProduct(
    p_Vendor_ID IN NUMBER,
    p_Name IN VARCHAR2,
    p_Category IN VARCHAR2,
    p_Version IN VARCHAR2 DEFAULT NULL
) IS
BEGIN
    INSERT INTO Products (Vendor_ID, Name, Category, Version)
    VALUES (p_Vendor_ID, p_Name, p_Category, p_Version);
END;
/

CREATE OR REPLACE PROCEDURE sp_AddLicense(
    p_Product_ID IN NUMBER,
    p_Purchase_Date IN DATE,
    p_Expiration_Date IN DATE DEFAULT NULL,
    p_Unit_Price IN NUMBER,
    p_Total_Seats IN NUMBER
) IS
BEGIN
    INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats)
    VALUES (p_Product_ID, p_Purchase_Date, p_Expiration_Date, p_Unit_Price, p_Total_Seats);
END;
/

CREATE OR REPLACE PROCEDURE sp_AddDevice(
    p_Location_ID IN NUMBER,
    p_Device_Type IN VARCHAR2,
    p_Purchase_Date IN DATE,
    p_Service_Life_Months IN NUMBER,
    p_Hostname IN VARCHAR2 DEFAULT NULL
) IS
BEGIN
    INSERT INTO Devices (Location_ID, Device_Type, Purchase_Date, Service_Life_Months, Hostname)
    VALUES (p_Location_ID, p_Device_Type, p_Purchase_Date, p_Service_Life_Months, p_Hostname);
END;
/

CREATE OR REPLACE PROCEDURE sp_AddInstallation(
    p_Device_ID IN NUMBER,
    p_License_ID IN NUMBER,
    p_Last_Activity_Date IN DATE DEFAULT NULL,
    p_Usage_Count IN NUMBER DEFAULT 0
) IS
BEGIN
    INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count)
    VALUES (p_Device_ID, p_License_ID, p_Last_Activity_Date, p_Usage_Count);
END;
/

CREATE OR REPLACE PROCEDURE sp_AddRequest(
    p_Product_ID IN NUMBER,
    p_User_Name IN VARCHAR2,
    p_User_Email IN VARCHAR2 DEFAULT NULL,
    p_Request_Date IN DATE DEFAULT SYSDATE,
    p_Status IN VARCHAR2 DEFAULT 'В ожидании'
) IS
BEGIN
    INSERT INTO Requests (Product_ID, User_Name, User_Email, Request_Date, Status)
    VALUES (p_Product_ID, p_User_Name, p_User_Email, p_Request_Date, p_Status);
END;
/

-- Продукты по поставщику
CREATE OR REPLACE FUNCTION fn_GetProductsByVendor(p_Vendor_ID IN NUMBER)
RETURN SYS_REFCURSOR IS
    rc SYS_REFCURSOR;
BEGIN
    OPEN rc FOR
        SELECT Product_ID, Name, Category, Version
        FROM Products
        WHERE Vendor_ID = p_Vendor_ID;
    RETURN rc;
END;
/

-- Лицензии по продукту
CREATE OR REPLACE FUNCTION fn_GetLicensesByProduct(p_Product_ID IN NUMBER)
RETURN SYS_REFCURSOR IS
    rc SYS_REFCURSOR;
BEGIN
    OPEN rc FOR
        SELECT License_ID, Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats
        FROM Licenses
        WHERE Product_ID = p_Product_ID;
    RETURN rc;
END;
/

-- Устройства по локации
CREATE OR REPLACE FUNCTION fn_GetDevicesByLocation(p_Location_ID IN NUMBER)
RETURN SYS_REFCURSOR IS
    rc SYS_REFCURSOR;
BEGIN
    OPEN rc FOR
        SELECT Device_ID, Device_Type, Purchase_Date, Service_Life_Months, Hostname
        FROM Devices
        WHERE Location_ID = p_Location_ID;
    RETURN rc;
END;
/

-- Установки по устройству
CREATE OR REPLACE FUNCTION fn_GetInstallationsByDevice(p_Device_ID IN NUMBER)
RETURN SYS_REFCURSOR IS
    rc SYS_REFCURSOR;
BEGIN
    OPEN rc FOR
        SELECT Install_ID, License_ID, Last_Activity_Date, Usage_Count
        FROM Installations
        WHERE Device_ID = p_Device_ID;
    RETURN rc;
END;
/

-- Запросы по продукту
CREATE OR REPLACE FUNCTION fn_GetRequestsByProduct(p_Product_ID IN NUMBER)
RETURN SYS_REFCURSOR IS
    rc SYS_REFCURSOR;
BEGIN
    OPEN rc FOR
        SELECT Request_ID, User_Name, User_Email, Request_Date, Status
        FROM Requests
        WHERE Product_ID = p_Product_ID;
    RETURN rc;
END;
/

-- Получить поставщика
CREATE OR REPLACE FUNCTION fn_GetVendor(p_Vendor_ID IN NUMBER)
RETURN SYS_REFCURSOR IS
    rc SYS_REFCURSOR;
BEGIN
    OPEN rc FOR
        SELECT Vendor_ID, Name, Email
        FROM Vendors
        WHERE Vendor_ID = p_Vendor_ID;
    RETURN rc;
END;
/

-- Активные лицензии
CREATE OR REPLACE FUNCTION fn_GetActiveLicenses
RETURN SYS_REFCURSOR IS
    rc SYS_REFCURSOR;
BEGIN
    OPEN rc FOR
        SELECT License_ID, Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats
        FROM Licenses
        WHERE Expiration_Date IS NULL OR Expiration_Date >= SYSDATE;
    RETURN rc;
END;
/