--Форматирование для print (чтобы не было лишних пробелов от varchar)
SET LINESIZE 200
SET PAGESIZE 50
SET TRIMOUT ON
SET TRIMSPOOL ON
COLUMN ProductName FORMAT A25
COLUMN Category    FORMAT A20
COLUMN Product     FORMAT A30
COLUMN Vendor      FORMAT A25
COLUMN Device_Type FORMAT A15

--Очистка 
DELETE FROM Requests;
DELETE FROM Installations;
DELETE FROM Devices;
DELETE FROM Licenses;
DELETE FROM Products;
DELETE FROM Locations;
DELETE FROM Vendors;

-- Сброс идентификаторов (identity-колонок).
ALTER TABLE Vendors       MODIFY (Vendor_ID       GENERATED BY DEFAULT AS IDENTITY (START WITH 1));
ALTER TABLE Locations     MODIFY (Location_ID     GENERATED BY DEFAULT AS IDENTITY (START WITH 1));
ALTER TABLE Products      MODIFY (Product_ID      GENERATED BY DEFAULT AS IDENTITY (START WITH 1));
ALTER TABLE Licenses      MODIFY (License_ID      GENERATED BY DEFAULT AS IDENTITY (START WITH 1));
ALTER TABLE Devices       MODIFY (Device_ID       GENERATED BY DEFAULT AS IDENTITY (START WITH 1));
ALTER TABLE Installations MODIFY (Install_ID      GENERATED BY DEFAULT AS IDENTITY (START WITH 1));
ALTER TABLE Requests      MODIFY (Request_ID      GENERATED BY DEFAULT AS IDENTITY (START WITH 1));

-- ---------------------------------------------------------------------
-- 1. Vendors
-- ---------------------------------------------------------------------
INSERT INTO Vendors (Name, Email) VALUES ('Microsoft',             'sales@microsoft.com');
INSERT INTO Vendors (Name, Email) VALUES ('Adobe',                 'sales@adobe.com');
INSERT INTO Vendors (Name, Email) VALUES ('JetBrains',             'sales@jetbrains.com');
INSERT INTO Vendors (Name, Email) VALUES ('Kaspersky',             'sales@kaspersky.com');
INSERT INTO Vendors (Name, Email) VALUES ('1C',                    'sales@1c.ru');
INSERT INTO Vendors (Name, Email) VALUES ('Autodesk',              'sales@autodesk.com');
INSERT INTO Vendors (Name, Email) VALUES ('Oracle',                'sales@oracle.com');
INSERT INTO Vendors (Name, Email) VALUES ('Positive Technologies', 'sales@ptsecurity.com');

-- ---------------------------------------------------------------------
-- 2. Locations
-- ---------------------------------------------------------------------
INSERT INTO Locations (Room_Number, Planned_Growth_Seats) VALUES ('101', 5);
INSERT INTO Locations (Room_Number, Planned_Growth_Seats) VALUES ('102', 3);
INSERT INTO Locations (Room_Number, Planned_Growth_Seats) VALUES ('201', 10);
INSERT INTO Locations (Room_Number, Planned_Growth_Seats) VALUES ('202', 0);
INSERT INTO Locations (Room_Number, Planned_Growth_Seats) VALUES ('203', 8);
INSERT INTO Locations (Room_Number, Planned_Growth_Seats) VALUES ('301', 4);
INSERT INTO Locations (Room_Number, Planned_Growth_Seats) VALUES ('302', 6);
INSERT INTO Locations (Room_Number, Planned_Growth_Seats) VALUES ('401', 0);
INSERT INTO Locations (Room_Number, Planned_Growth_Seats) VALUES ('402', 2);
INSERT INTO Locations (Room_Number, Planned_Growth_Seats) VALUES ('Серверная', 0);

-- ---------------------------------------------------------------------
-- 3. Products
-- ---------------------------------------------------------------------
INSERT INTO Products (Vendor_ID, Name, Category, Version) VALUES (1, 'Windows 11 Pro',            'Офисное',        '23H2');
INSERT INTO Products (Vendor_ID, Name, Category, Version) VALUES (1, 'Microsoft Office 365',      'Офисное',        '2024');
INSERT INTO Products (Vendor_ID, Name, Category, Version) VALUES (1, 'Visual Studio Professional','Разработка',     '2022');
INSERT INTO Products (Vendor_ID, Name, Category, Version) VALUES (1, 'SQL Server Developer',      'СУБД',           '2022');
INSERT INTO Products (Vendor_ID, Name, Category, Version) VALUES (2, 'Adobe Photoshop',           'Графика',        '2024');
INSERT INTO Products (Vendor_ID, Name, Category, Version) VALUES (2, 'Adobe Illustrator',         'Графика',        '2024');
INSERT INTO Products (Vendor_ID, Name, Category, Version) VALUES (2, 'Adobe Premiere Pro',        'Графика',        '2024');
INSERT INTO Products (Vendor_ID, Name, Category, Version) VALUES (3, 'IntelliJ IDEA Ultimate',    'Разработка',     '2024.1');
INSERT INTO Products (Vendor_ID, Name, Category, Version) VALUES (3, 'PyCharm Professional',      'Разработка',     '2024.1');
INSERT INTO Products (Vendor_ID, Name, Category, Version) VALUES (3, 'DataGrip',                  'СУБД',           '2024.1');
INSERT INTO Products (Vendor_ID, Name, Category, Version) VALUES (4, 'Kaspersky Endpoint Security','Безопасность',  '12.0');
INSERT INTO Products (Vendor_ID, Name, Category, Version) VALUES (4, 'Kaspersky Total Security',  'Безопасность',   '2024');
INSERT INTO Products (Vendor_ID, Name, Category, Version) VALUES (5, '1С:Предприятие',            'Учёт',           '8.3');
INSERT INTO Products (Vendor_ID, Name, Category, Version) VALUES (5, '1С:Бухгалтерия',            'Учёт',           '3.0');
INSERT INTO Products (Vendor_ID, Name, Category, Version) VALUES (6, 'AutoCAD',                   'Проектирование', '2024');
INSERT INTO Products (Vendor_ID, Name, Category, Version) VALUES (6, '3ds Max',                   'Проектирование', '2024');
INSERT INTO Products (Vendor_ID, Name, Category, Version) VALUES (7, 'Oracle Database SE',        'СУБД',           '21c');
INSERT INTO Products (Vendor_ID, Name, Category, Version) VALUES (7, 'Oracle Java SE',            'Разработка',     '21');
INSERT INTO Products (Vendor_ID, Name, Category, Version) VALUES (8, 'MaxPatrol SIEM',            'Безопасность',   '7.0');
INSERT INTO Products (Vendor_ID, Name, Category, Version) VALUES (8, 'PT Application Firewall',   'Безопасность',   '4.0');

-- ---------------------------------------------------------------------
-- 4. Licenses
-- В Oracle даты задаются через DATE '....' или TO_DATE(...)
-- ---------------------------------------------------------------------
-- Product 1: классический UP-DOWN-UP, плюс ещё один UP-DOWN-UP в конце (2 матча)
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (1, DATE '2023-01-15', DATE '2026-01-15', 12000, 20);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (1, DATE '2023-05-10', DATE '2026-05-10', 12500, 15);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (1, DATE '2023-09-20', DATE '2026-09-20', 11000, 10);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (1, DATE '2024-02-05', DATE '2027-02-05', 11500, 12);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (1, DATE '2024-07-15', DATE '2027-07-15', 14000, 18);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (1, DATE '2025-03-01', DATE '2028-03-01', 12500, 10);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (1, DATE '2025-10-10', DATE '2028-10-10', 13000, 8);

-- Product 2: только монотонный рост (матча НЕ должно быть)
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (2, DATE '2023-02-01', DATE '2024-02-01', 5000, 25);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (2, DATE '2023-06-15', DATE '2024-06-15', 5200, 20);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (2, DATE '2023-11-05', DATE '2024-11-05', 5400, 30);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (2, DATE '2024-03-10', DATE '2025-03-10', 5600, 15);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (2, DATE '2024-08-20', DATE '2025-08-20', 5800, 25);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (2, DATE '2025-01-25', DATE '2026-01-25', 6000, 20);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (2, DATE '2025-09-30', DATE '2026-09-30', 6200, 35);

-- Product 3: DOWN-UP-DOWN (обратный паттерн, матча НЕ должно быть)
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (3, DATE '2023-03-20', DATE '2026-03-20', 48000, 8);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (3, DATE '2023-07-10', DATE '2026-07-10', 46000, 10);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (3, DATE '2024-01-15', DATE '2027-01-15', 43000, 6);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (3, DATE '2024-06-15', DATE '2027-06-15', 47000, 10);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (3, DATE '2025-04-01', DATE '2028-04-01', 41000, 7);

-- Product 4: бесплатное ПО, все цены = 0 (все FLAT, матча нет)
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (4, DATE '2023-04-10', NULL, 0, 40);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (4, DATE '2023-10-01', NULL, 0, 60);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (4, DATE '2024-05-05', NULL, 0, 50);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (4, DATE '2025-01-01', NULL, 0, 55);

-- Product 5: классический UP-DOWN-UP (один матч)
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (5, DATE '2023-05-01', DATE '2024-05-01', 16000, 10);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (5, DATE '2023-12-01', DATE '2024-12-01', 18000, 12);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (5, DATE '2024-04-10', DATE '2025-04-10', 17000, 15);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (5, DATE '2024-09-15', DATE '2025-09-15', 16500, 12);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (5, DATE '2025-02-20', DATE '2026-02-20', 19000, 8);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (5, DATE '2025-11-05', DATE '2026-11-05', 21000, 6);

-- Product 6: только монотонный рост (матча НЕ должно быть)
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (6, DATE '2023-06-01', DATE '2024-06-01', 18000, 8);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (6, DATE '2023-08-15', DATE '2024-08-15', 18500, 10);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (6, DATE '2024-02-10', DATE '2025-02-10', 19000, 7);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (6, DATE '2024-08-20', DATE '2025-08-20', 19500, 10);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (6, DATE '2025-03-15', DATE '2026-03-15', 20000, 6);

-- Product 7: только монотонный рост (матча НЕ должно быть)
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (7, DATE '2023-01-10', DATE '2024-01-10', 22000, 5);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (7, DATE '2023-07-01', DATE '2024-07-01', 22500, 7);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (7, DATE '2024-01-10', DATE '2025-01-10', 23000, 6);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (7, DATE '2024-10-10', DATE '2025-10-10', 23500, 5);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (7, DATE '2025-06-01', DATE '2026-06-01', 24000, 4);

-- Product 8: только монотонный рост (матча НЕ должно быть)
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (8, DATE '2023-02-01', DATE '2024-02-01', 25000, 12);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (8, DATE '2023-09-01', DATE '2024-09-01', 25500, 15);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (8, DATE '2024-03-01', DATE '2025-03-01', 26000, 10);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (8, DATE '2024-09-05', DATE '2025-09-05', 27000, 15);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (8, DATE '2025-05-01', DATE '2026-05-01', 28000, 12);

-- Product 9 (PyCharm): UP-DOWN-UP с длинными сериями (проверка жадности +)
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (9, DATE '2023-01-10', DATE '2024-01-10', 15000, 10);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (9, DATE '2023-05-10', DATE '2024-05-10', 16000, 10);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (9, DATE '2023-10-01', DATE '2024-10-01', 18000, 10);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (9, DATE '2024-02-15', DATE '2025-02-15', 17000, 12);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (9, DATE '2024-06-15', DATE '2025-06-15', 16000, 12);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (9, DATE '2024-10-10', DATE '2025-10-10', 19500, 12);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (9, DATE '2025-04-01', DATE '2026-04-01', 21000, 14);

-- Product 10 (DataGrip): только 3 строки, формально UP-DOWN-UP не складывается (мало данных)
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (10, DATE '2024-01-20', DATE '2025-01-20', 15000, 8);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (10, DATE '2024-08-20', DATE '2025-08-20', 16000, 8);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (10, DATE '2025-03-20', DATE '2026-03-20', 14500, 10);

-- Product 11 (Kaspersky Endpoint): ДВА матча подряд UP-DOWN-UP / UP-DOWN-UP
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (11, DATE '2023-03-01', DATE '2024-03-01', 3500, 50);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (11, DATE '2023-07-01', DATE '2024-07-01', 3800, 50);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (11, DATE '2023-11-01', DATE '2024-11-01', 3600, 50);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (11, DATE '2024-03-05', DATE '2025-03-05', 4100, 50);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (11, DATE '2024-07-05', DATE '2025-07-05', 4300, 55);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (11, DATE '2024-11-05', DATE '2025-11-05', 4000, 55);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (11, DATE '2025-03-10', DATE '2026-03-10', 4500, 55);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (11, DATE '2025-09-10', DATE '2026-09-10', 4700, 60);

-- Product 12 (Kaspersky Total): UP-FLAT-DOWN-UP (FLAT должен порвать паттерн перед FLAT)
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (12, DATE '2023-05-15', DATE '2024-05-15', 4800, 20);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (12, DATE '2023-11-15', DATE '2024-11-15', 5000, 20);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (12, DATE '2024-05-15', DATE '2025-05-15', 5000, 20);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (12, DATE '2024-11-20', DATE '2025-11-20', 4700, 25);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (12, DATE '2025-05-20', DATE '2026-05-20', 5500, 25);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (12, DATE '2025-11-20', DATE '2026-11-20', 5800, 25);

-- Product 13 (1С:Предприятие): UP-DOWN-UP, аккуратный матч
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (13, DATE '2023-08-01', NULL, 35000, 5);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (13, DATE '2024-02-01', NULL, 37000, 5);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (13, DATE '2024-08-01', NULL, 34000, 6);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (13, DATE '2025-02-01', NULL, 36000, 6);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (13, DATE '2025-08-01', NULL, 39000, 7);

-- Product 14 (1С:Бухгалтерия): только 2 строки (мало данных, матча нет)
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (14, DATE '2023-08-01', NULL, 28000, 3);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (14, DATE '2024-08-01', NULL, 30000, 3);

-- Product 15 (AutoCAD): ДВА матча UP-DOWN-UP
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (15, DATE '2023-06-01', DATE '2024-06-01', 80000, 10);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (15, DATE '2023-12-01', DATE '2024-12-01', 85000, 10);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (15, DATE '2024-06-01', DATE '2025-06-01', 82000, 10);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (15, DATE '2024-12-10', DATE '2025-12-10', 90000, 10);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (15, DATE '2025-04-10', DATE '2026-04-10', 95000, 10);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (15, DATE '2025-08-10', DATE '2026-08-10', 88000, 10);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (15, DATE '2025-12-10', DATE '2026-12-10', 100000, 12);

-- Product 16 (3ds Max): длинная серия роста (UP+ жадный) → DOWN → UP
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (16, DATE '2023-04-15', DATE '2024-04-15', 88000, 5);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (16, DATE '2023-10-15', DATE '2024-10-15', 90000, 5);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (16, DATE '2024-04-15', DATE '2025-04-15', 95000, 5);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (16, DATE '2024-10-15', DATE '2025-10-15', 98000, 6);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (16, DATE '2025-04-15', DATE '2026-04-15', 92000, 6);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (16, DATE '2025-10-15', DATE '2026-10-15', 99000, 6);

-- Product 17 (Oracle DB SE): только монотонное падение (матча НЕ должно быть)
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (17, DATE '2023-06-01', DATE '2025-06-01', 160000, 2);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (17, DATE '2023-12-01', DATE '2025-12-01', 155000, 2);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (17, DATE '2024-06-01', DATE '2026-06-01', 150000, 2);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (17, DATE '2024-12-01', DATE '2026-12-01', 145000, 2);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (17, DATE '2025-06-01', DATE '2027-06-01', 140000, 2);

-- Product 18 (Oracle Java SE): UP-FLAT-DOWN-UP (FLAT в середине рвёт паттерн)
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (18, DATE '2023-07-01', DATE '2024-07-01', 7500, 20);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (18, DATE '2024-01-01', DATE '2025-01-01', 8000, 20);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (18, DATE '2024-07-01', DATE '2025-07-01', 8000, 20);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (18, DATE '2025-01-01', DATE '2026-01-01', 7800, 20);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (18, DATE '2025-07-01', DATE '2026-07-01', 8500, 20);

-- Product 19 (MaxPatrol SIEM): UP-DOWN-UP, минимально возможное число строк (4)
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (19, DATE '2024-02-01', DATE '2025-02-01', 250000, 1);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (19, DATE '2024-08-01', DATE '2025-08-01', 270000, 1);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (19, DATE '2025-02-01', DATE '2026-02-01', 260000, 1);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (19, DATE '2025-08-01', DATE '2026-08-01', 280000, 1);

-- Product 20 (PT Application Firewall): только 1 строка (матча нет, партиция вырожденная)
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (20, DATE '2024-09-01', DATE '2025-09-01', 180000, 1);

-- ---------------------------------------------------------------------
-- 5. Devices
-- ---------------------------------------------------------------------
INSERT INTO Devices (Location_ID, Device_Type, Purchase_Date, Service_Life_Months, Hostname) VALUES (1, 'ПК',      DATE '2022-09-01', 60, 'PC-101-01');
INSERT INTO Devices (Location_ID, Device_Type, Purchase_Date, Service_Life_Months, Hostname) VALUES (1, 'ПК',      DATE '2022-09-01', 60, 'PC-101-02');
INSERT INTO Devices (Location_ID, Device_Type, Purchase_Date, Service_Life_Months, Hostname) VALUES (1, 'ПК',      DATE '2022-09-01', 60, 'PC-101-03');
INSERT INTO Devices (Location_ID, Device_Type, Purchase_Date, Service_Life_Months, Hostname) VALUES (1, 'ПК',      DATE '2023-09-01', 60, 'PC-101-04');
INSERT INTO Devices (Location_ID, Device_Type, Purchase_Date, Service_Life_Months, Hostname) VALUES (1, 'ПК',      DATE '2023-09-01', 60, 'PC-101-05');
INSERT INTO Devices (Location_ID, Device_Type, Purchase_Date, Service_Life_Months, Hostname) VALUES (2, 'ПК',      DATE '2023-01-15', 60, 'PC-102-01');
INSERT INTO Devices (Location_ID, Device_Type, Purchase_Date, Service_Life_Months, Hostname) VALUES (2, 'ПК',      DATE '2023-01-15', 60, 'PC-102-02');
INSERT INTO Devices (Location_ID, Device_Type, Purchase_Date, Service_Life_Months, Hostname) VALUES (2, 'ПК',      DATE '2023-01-15', 60, 'PC-102-03');
INSERT INTO Devices (Location_ID, Device_Type, Purchase_Date, Service_Life_Months, Hostname) VALUES (3, 'ПК',      DATE '2021-09-01', 60, 'PC-201-01');
INSERT INTO Devices (Location_ID, Device_Type, Purchase_Date, Service_Life_Months, Hostname) VALUES (3, 'ПК',      DATE '2021-09-01', 60, 'PC-201-02');
INSERT INTO Devices (Location_ID, Device_Type, Purchase_Date, Service_Life_Months, Hostname) VALUES (3, 'ПК',      DATE '2021-09-01', 60, 'PC-201-03');
INSERT INTO Devices (Location_ID, Device_Type, Purchase_Date, Service_Life_Months, Hostname) VALUES (3, 'ПК',      DATE '2023-03-01', 60, 'PC-201-04');
INSERT INTO Devices (Location_ID, Device_Type, Purchase_Date, Service_Life_Months, Hostname) VALUES (3, 'ПК',      DATE '2023-03-01', 60, 'PC-201-05');
INSERT INTO Devices (Location_ID, Device_Type, Purchase_Date, Service_Life_Months, Hostname) VALUES (4, 'Ноутбук', DATE '2023-06-01', 48, 'NB-202-01');
INSERT INTO Devices (Location_ID, Device_Type, Purchase_Date, Service_Life_Months, Hostname) VALUES (4, 'Ноутбук', DATE '2023-06-01', 48, 'NB-202-02');
INSERT INTO Devices (Location_ID, Device_Type, Purchase_Date, Service_Life_Months, Hostname) VALUES (4, 'Ноутбук', DATE '2024-01-10', 48, 'NB-202-03');
INSERT INTO Devices (Location_ID, Device_Type, Purchase_Date, Service_Life_Months, Hostname) VALUES (5, 'ПК',      DATE '2022-01-15', 60, 'PC-203-01');
INSERT INTO Devices (Location_ID, Device_Type, Purchase_Date, Service_Life_Months, Hostname) VALUES (5, 'ПК',      DATE '2022-01-15', 60, 'PC-203-02');
INSERT INTO Devices (Location_ID, Device_Type, Purchase_Date, Service_Life_Months, Hostname) VALUES (5, 'ПК',      DATE '2024-02-01', 60, 'PC-203-03');
INSERT INTO Devices (Location_ID, Device_Type, Purchase_Date, Service_Life_Months, Hostname) VALUES (5, 'ПК',      DATE '2024-02-01', 60, 'PC-203-04');
INSERT INTO Devices (Location_ID, Device_Type, Purchase_Date, Service_Life_Months, Hostname) VALUES (6, 'ПК',      DATE '2023-09-01', 60, 'PC-301-01');
INSERT INTO Devices (Location_ID, Device_Type, Purchase_Date, Service_Life_Months, Hostname) VALUES (6, 'ПК',      DATE '2023-09-01', 60, 'PC-301-02');
INSERT INTO Devices (Location_ID, Device_Type, Purchase_Date, Service_Life_Months, Hostname) VALUES (6, 'ПК',      DATE '2024-09-01', 60, 'PC-301-03');
INSERT INTO Devices (Location_ID, Device_Type, Purchase_Date, Service_Life_Months, Hostname) VALUES (7, 'Ноутбук', DATE '2024-03-01', 48, 'NB-302-01');
INSERT INTO Devices (Location_ID, Device_Type, Purchase_Date, Service_Life_Months, Hostname) VALUES (7, 'Ноутбук', DATE '2024-03-01', 48, 'NB-302-02');
INSERT INTO Devices (Location_ID, Device_Type, Purchase_Date, Service_Life_Months, Hostname) VALUES (10, 'Сервер', DATE '2021-06-01', 84, 'SRV-01');
INSERT INTO Devices (Location_ID, Device_Type, Purchase_Date, Service_Life_Months, Hostname) VALUES (10, 'Сервер', DATE '2022-12-01', 84, 'SRV-02');
INSERT INTO Devices (Location_ID, Device_Type, Purchase_Date, Service_Life_Months, Hostname) VALUES (10, 'Сервер', DATE '2024-06-01', 84, 'SRV-03');

-- ---------------------------------------------------------------------
-- 6. Installations
-- ---------------------------------------------------------------------
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (1,  1,  DATE '2025-03-28', 450);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (2,  1,  DATE '2025-03-27', 430);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (3,  1,  DATE '2025-03-28', 410);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (4,  2,  DATE '2025-03-26', 380);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (5,  2,  DATE '2025-03-28', 395);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (6,  1,  DATE '2025-03-25', 350);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (7,  1,  DATE '2025-03-28', 360);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (8,  1,  DATE '2025-03-27', 340);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (1,  4,  DATE '2025-03-28', 500);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (2,  4,  DATE '2025-03-27', 480);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (3,  4,  DATE '2025-03-28', 490);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (6,  5,  DATE '2025-03-25', 310);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (7,  5,  DATE '2025-03-28', 320);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (9,  5,  DATE '2025-03-20', 280);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (10, 5,  DATE '2025-03-22', 260);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (9,  7,  DATE '2025-03-15', 120);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (10, 7,  DATE '2025-03-18', 140);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (11, 7,  DATE '2025-03-20', 110);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (12, 8,  DATE '2025-03-25', 95);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (13, 8,  DATE '2025-03-28', 105);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (17, 10, DATE '2025-03-22', 85);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (18, 11, DATE '2025-03-28', 92);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (19, 11, DATE '2025-03-27', 78);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (20, 12, DATE '2025-02-10', 45);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (17, 13, DATE '2025-03-20', 60);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (18, 14, DATE '2025-03-25', 72);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (19, 14, DATE '2025-03-28', 55);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (14, 15, DATE '2025-03-18', 30);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (15, 16, DATE '2025-03-28', 42);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (9,  17, DATE '2025-03-10', 200);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (10, 17, DATE '2025-03-15', 190);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (11, 18, DATE '2025-03-28', 175);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (12, 18, DATE '2025-03-26', 160);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (21, 19, DATE '2025-03-12', 140);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (22, 20, DATE '2025-03-28', 155);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (23, 20, DATE '2025-03-25', 130);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (24, 21, DATE '2025-03-20', 60);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (25, 21, DATE '2025-03-28', 55);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (1,  22, DATE '2025-03-28', 500);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (2,  22, DATE '2025-03-28', 490);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (3,  22, DATE '2025-03-28', 480);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (6,  23, DATE '2025-03-28', 470);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (7,  23, DATE '2025-03-28', 460);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (9,  23, DATE '2025-03-28', 440);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (10, 23, DATE '2025-03-28', 430);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (11, 24, DATE '2025-03-28', 200);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (17, 24, DATE '2025-03-28', 210);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (14, 25, DATE '2025-03-28', 300);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (15, 25, DATE '2025-03-28', 290);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (16, 26, DATE '2025-03-28', 150);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (21, 27, DATE '2025-03-20', 250);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (22, 27, DATE '2025-03-22', 240);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (23, 28, DATE '2025-03-18', 180);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (17, 29, DATE '2025-03-15', 70);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (18, 30, DATE '2025-03-28', 85);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (19, 30, DATE '2025-03-25', 65);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (20, 30, DATE '2025-03-20', 50);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (26, 9,  DATE '2025-03-28', 1000);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (27, 9,  DATE '2025-03-28', 950);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (28, 33, DATE '2025-03-28', 800);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (26, 34, DATE '2025-03-28', 600);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (27, 35, DATE '2025-03-28', 550);

-- ---------------------------------------------------------------------
-- 7. Requests
-- В Oracle префикс N'...' не нужен: если колонка NVARCHAR2/VARCHAR2
-- с поддержкой национального набора, литерал можно писать обычным образом.
-- ---------------------------------------------------------------------
INSERT INTO Requests (Product_ID, User_Name, User_Email, Request_Date, Status) VALUES (2,  'Иванов А.С.',    'ivanov@univ.ru',    DATE '2024-09-01', 'Одобрено');
INSERT INTO Requests (Product_ID, User_Name, User_Email, Request_Date, Status) VALUES (2,  'Иванов А.С.',    'ivanov@univ.ru',    DATE '2024-09-01', 'Одобрено');
INSERT INTO Requests (Product_ID, User_Name, User_Email, Request_Date, Status) VALUES (5,  'Сидоров К.Л.',   'sidorov@univ.ru',   DATE '2024-09-10', 'Одобрено');
INSERT INTO Requests (Product_ID, User_Name, User_Email, Request_Date, Status) VALUES (5,  'Сидоров К.Л.',   'sidorov@univ.ru',   DATE '2024-09-10', 'Одобрено');
INSERT INTO Requests (Product_ID, User_Name, User_Email, Request_Date, Status) VALUES (3,  'Петрова М.В.',   'petrova@univ.ru',   DATE '2024-09-05', 'Одобрено');
INSERT INTO Requests (Product_ID, User_Name, User_Email, Request_Date, Status) VALUES (3,  'Петрова М.В.',   'petrova@univ.ru',   DATE '2024-09-05', 'Одобрено');
INSERT INTO Requests (Product_ID, User_Name, User_Email, Request_Date, Status) VALUES (8,  'Козлов Д.А.',    'kozlov@univ.ru',    DATE '2024-09-15', 'Одобрено');
INSERT INTO Requests (Product_ID, User_Name, User_Email, Request_Date, Status) VALUES (15, 'Морозова Е.И.',  'morozova@univ.ru',  DATE '2024-10-01', 'Одобрено');
INSERT INTO Requests (Product_ID, User_Name, User_Email, Request_Date, Status) VALUES (9,  'Волков Р.С.',    'volkov@univ.ru',    DATE '2024-10-10', 'Одобрено');
INSERT INTO Requests (Product_ID, User_Name, User_Email, Request_Date, Status) VALUES (6,  'Новикова А.П.',  'novikova@univ.ru',  DATE '2024-10-15', 'Одобрено');
INSERT INTO Requests (Product_ID, User_Name, User_Email, Request_Date, Status) VALUES (7,  'Фёдоров И.М.',   'fedorov@univ.ru',   DATE '2024-11-01', 'Одобрено');
INSERT INTO Requests (Product_ID, User_Name, User_Email, Request_Date, Status) VALUES (16, 'Алексеева Т.Н.', 'alekseeva@univ.ru', DATE '2024-11-10', 'Отклонено');
INSERT INTO Requests (Product_ID, User_Name, User_Email, Request_Date, Status) VALUES (10, 'Егоров В.В.',    'egorov@univ.ru',    DATE '2024-11-20', 'Одобрено');
INSERT INTO Requests (Product_ID, User_Name, User_Email, Request_Date, Status) VALUES (13, 'Дмитриева О.С.', 'dmitrieva@univ.ru', DATE '2024-12-01', 'Одобрено');
INSERT INTO Requests (Product_ID, User_Name, User_Email, Request_Date, Status) VALUES (2,  'Кузнецов П.А.',  'kuznetsov@univ.ru', DATE '2024-12-05', 'В ожидании');
INSERT INTO Requests (Product_ID, User_Name, User_Email, Request_Date, Status) VALUES (5,  'Попова Л.Г.',    'popova@univ.ru',    DATE '2024-12-10', 'В ожидании');
INSERT INTO Requests (Product_ID, User_Name, User_Email, Request_Date, Status) VALUES (3,  'Соколов А.Р.',   'sokolov@univ.ru',   DATE '2025-01-10', 'Одобрено');
INSERT INTO Requests (Product_ID, User_Name, User_Email, Request_Date, Status) VALUES (11, 'Лебедева Н.К.',  'lebedeva@univ.ru',  DATE '2025-01-15', 'Одобрено');
INSERT INTO Requests (Product_ID, User_Name, User_Email, Request_Date, Status) VALUES (15, 'Михайлов С.Д.',  'mikhailov@univ.ru', DATE '2025-01-20', 'В ожидании');
INSERT INTO Requests (Product_ID, User_Name, User_Email, Request_Date, Status) VALUES (8,  'Новиков Е.А.',   'novikov@univ.ru',   DATE '2025-02-01', 'Одобрено');
INSERT INTO Requests (Product_ID, User_Name, User_Email, Request_Date, Status) VALUES (19, 'Зайцев О.П.',    'zaytsev@univ.ru',   DATE '2025-02-05', 'Отклонено');
INSERT INTO Requests (Product_ID, User_Name, User_Email, Request_Date, Status) VALUES (20, 'Борисова Д.Л.',  'borisova@univ.ru',  DATE '2025-02-10', 'Отклонено');
INSERT INTO Requests (Product_ID, User_Name, User_Email, Request_Date, Status) VALUES (2,  'Григорьев К.М.', 'grigoriev@univ.ru', DATE '2025-02-15', 'Одобрено');
INSERT INTO Requests (Product_ID, User_Name, User_Email, Request_Date, Status) VALUES (9,  'Романова В.И.',  'romanova@univ.ru',  DATE '2025-02-20', 'В ожидании');
INSERT INTO Requests (Product_ID, User_Name, User_Email, Request_Date, Status) VALUES (14, 'Васильев Н.С.',  'vasiliev@univ.ru',  DATE '2025-03-01', 'Одобрено');
INSERT INTO Requests (Product_ID, User_Name, User_Email, Request_Date, Status) VALUES (1,  'Павлова А.М.',   'pavlova@univ.ru',   DATE '2025-03-05', 'В ожидании');
INSERT INTO Requests (Product_ID, User_Name, User_Email, Request_Date, Status) VALUES (17, 'Семёнов Д.В.',   'semenov@univ.ru',   DATE '2025-03-10', 'Отклонено');
INSERT INTO Requests (Product_ID, User_Name, User_Email, Request_Date, Status) VALUES (4,  'Голубева И.Р.',  'golubeva@univ.ru',  DATE '2025-03-15', 'Одобрено');

COMMIT;

SELECT * FROM Requests;
SELECT * FROM Installations;
SELECT * FROM Devices;
SELECT * FROM Licenses;
SELECT * FROM Products;
SELECT * FROM Locations;
SELECT * FROM Vendors;

-- 3. Итоги стоимости определённого вида ПО помесячно,
-- за квартал, за полгода, за год. Oracle-версия хранимой процедуры.
CREATE OR REPLACE PROCEDURE sp_ProductCostByPeriod (
    p_Product_ID IN NUMBER,
    p_StartDate IN DATE,
    p_EndDate IN DATE,
    p_Cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_Cursor FOR
        WITH src AS (
            SELECT
                p.Name AS ProductName,
                EXTRACT(YEAR  FROM l.Purchase_Date) AS Yr,
                EXTRACT(MONTH FROM l.Purchase_Date) AS Mn,
                TO_NUMBER(TO_CHAR(l.Purchase_Date, 'Q')) AS Qr,
                CASE WHEN EXTRACT(MONTH FROM l.Purchase_Date) <= 6
                     THEN 1 ELSE 2 END AS Hf,
                l.Total_Seats AS TotalSeats,
                l.Unit_Price AS UnitPrice
            FROM Licenses l
                 JOIN Products p ON l.Product_ID = p.Product_ID
            WHERE l.Product_ID = p_Product_ID
              AND l.Purchase_Date BETWEEN p_StartDate AND p_EndDate
        )
        SELECT
            ProductName,
            Yr AS Yr,
            CASE WHEN GROUPING(Mn) = 0 THEN Mn END AS Mn,
            CASE WHEN GROUPING(Qr) = 0 THEN Qr END AS Qr,
            CASE WHEN GROUPING(Hf) = 0 THEN Hf END AS Hf,
            SUM(TotalSeats) AS TotalLicenses,
            SUM(TotalSeats * UnitPrice) AS TotalCost
        FROM src
        GROUP BY GROUPING SETS (
            (ProductName, Yr, Mn),
            (ProductName, Yr, Qr),
            (ProductName, Yr, Hf),
            (ProductName, Yr)
        )
        ORDER BY Yr, Mn, Qr, Hf;
END;
/

VARIABLE rc REFCURSOR;
EXEC sp_ProductCostByPeriod(2, DATE '2023-01-01', DATE '2025-12-31', :rc);
PRINT rc;

SELECT * FROM Licenses WHERE Product_ID = 2;

-- 4. Вычисление итогов стоимости ПО за период:
--   количество и стоимость лицензий;
--   их доля в общем количестве лицензий (%);
--   их доля в общей стоимости лицензий (%).
CREATE OR REPLACE PROCEDURE sp_LicenseCostAnalysis (
    p_DateFrom IN DATE DEFAULT DATE '2023-01-01',
    p_DateTo IN DATE DEFAULT DATE '2025-12-31',
    p_Cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_Cursor FOR
        SELECT
            p.Category AS Category,
            p.Name AS Product,
            EXTRACT(YEAR FROM l.Purchase_Date) AS Yr,
            COUNT(*) AS Lic_Count,
            SUM(l.Unit_Price * l.Total_Seats) AS Total_Cost,

            CAST( COUNT(*) * 100 / SUM(COUNT(*)) OVER ()
                  AS NUMBER(5,2)
            ) AS Pct_Of_Count,

            CAST( SUM(l.Unit_Price * l.Total_Seats) * 100 /
                SUM(SUM(l.Unit_Price * l.Total_Seats)) OVER ()
                AS NUMBER(5,2)
            ) AS Pct_Of_Cost

        FROM Licenses l
             JOIN Products p ON l.Product_ID = p.Product_ID
        WHERE l.Purchase_Date BETWEEN p_DateFrom AND p_DateTo
        GROUP BY p.Category, p.Name, EXTRACT(YEAR FROM l.Purchase_Date)
        ORDER BY p.Category, p.Name, Yr;
END;
/

VARIABLE rc2 REFCURSOR;
EXEC sp_LicenseCostAnalysis(DATE '2024-01-01', DATE '2024-12-31', :rc2);
PRINT rc2;

-- 7. Для каждого вендора – суммы затрат на лицензирование
-- за последние 6 месяцев помесячно (накопительное окно 6 периодов).
CREATE OR REPLACE PROCEDURE sp_VendorCostLast6Months (
    p_Cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_Cursor FOR
        SELECT
            v.Name AS Vendor,
            EXTRACT(YEAR  FROM l.Purchase_Date) AS Yr,
            EXTRACT(MONTH FROM l.Purchase_Date) AS Mn,
            SUM(l.Unit_Price * l.Total_Seats) AS Monthly_Cost,

            SUM(SUM(l.Unit_Price * l.Total_Seats)) OVER (
                PARTITION BY v.Vendor_ID
                ORDER BY EXTRACT(YEAR  FROM l.Purchase_Date),
                         EXTRACT(MONTH FROM l.Purchase_Date)
                ROWS BETWEEN 5 PRECEDING AND CURRENT ROW
            ) AS Sum_Last_6_Months

        FROM Licenses l
             JOIN Products p ON l.Product_ID = p.Product_ID
             JOIN Vendors  v ON p.Vendor_ID  = v.Vendor_ID
        GROUP BY v.Vendor_ID, v.Name, EXTRACT(YEAR  FROM l.Purchase_Date),
            EXTRACT(MONTH FROM l.Purchase_Date)
        ORDER BY v.Name, Yr, Mn;
END;
/

VARIABLE rc3 REFCURSOR;
EXEC sp_VendorCostLast6Months(:rc3);
PRINT rc3;


-- 8. Какой тип ПО (категория) использовался наибольшее число
-- раз для устройств определённого вида? Вернуть для всех видов устройств.
CREATE OR REPLACE PROCEDURE sp_TopCategoryByDeviceType (
    p_Cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_Cursor FOR
        WITH cte AS (
            SELECT
                d.Device_Type AS Device_Type,
                p.Category AS Category,
                COUNT(*) AS Install_Count,
                ROW_NUMBER() OVER (
                    PARTITION BY d.Device_Type
                    ORDER BY COUNT(*) DESC
                ) AS rn
            FROM Installations i
                 JOIN Devices  d ON i.Device_ID  = d.Device_ID
                 JOIN Licenses l ON i.License_ID = l.License_ID
                 JOIN Products p ON l.Product_ID = p.Product_ID
            GROUP BY d.Device_Type, p.Category
        )
        SELECT Device_Type, Category, Install_Count
        FROM cte
        WHERE rn = 1;
END;
/

VARIABLE rc4 REFCURSOR;
EXEC sp_TopCategoryByDeviceType(:rc4);
PRINT rc4;