--Форматирование для print (чтобы не было лишних пробелов от varchar)
SET LINESIZE 200
SET PAGESIZE 50
SET TRIMOUT ON
SET TRIMSPOOL ON
COLUMN ProductName FORMAT A25
COLUMN Category    FORMAT A20
COLUMN Product     FORMAT A30
COLUMN Vendor      FORMAT A25
COLUMN Device_Type FORMAT A15

-- Очистка данных
DELETE FROM Requests;
DELETE FROM Installations;
DELETE FROM Devices;
DELETE FROM Licenses;
DELETE FROM Products;
DELETE FROM Locations;
DELETE FROM Vendors;

COMMIT;

ALTER TABLE Vendors       MODIFY (Vendor_ID       GENERATED BY DEFAULT AS IDENTITY (START WITH 1));
ALTER TABLE Locations     MODIFY (Location_ID     GENERATED BY DEFAULT AS IDENTITY (START WITH 1));
ALTER TABLE Products      MODIFY (Product_ID      GENERATED BY DEFAULT AS IDENTITY (START WITH 1));
ALTER TABLE Licenses      MODIFY (License_ID      GENERATED BY DEFAULT AS IDENTITY (START WITH 1));
ALTER TABLE Devices       MODIFY (Device_ID       GENERATED BY DEFAULT AS IDENTITY (START WITH 1));
ALTER TABLE Installations MODIFY (Install_ID      GENERATED BY DEFAULT AS IDENTITY (START WITH 1));
ALTER TABLE Requests      MODIFY (Request_ID      GENERATED BY DEFAULT AS IDENTITY (START WITH 1));

-- Загрузка данных

-- 1. Vendors
INSERT INTO Vendors (Name, Email) VALUES ('Microsoft',        'sales@microsoft.com');
INSERT INTO Vendors (Name, Email) VALUES ('Adobe',            'sales@adobe.com');
INSERT INTO Vendors (Name, Email) VALUES ('JetBrains',        'sales@jetbrains.com');
INSERT INTO Vendors (Name, Email) VALUES ('Kaspersky',        'sales@kaspersky.com');
INSERT INTO Vendors (Name, Email) VALUES ('1C',               'sales@1c.ru');
INSERT INTO Vendors (Name, Email) VALUES ('Autodesk',         'sales@autodesk.com');
INSERT INTO Vendors (Name, Email) VALUES ('Oracle',           'sales@oracle.com');
INSERT INTO Vendors (Name, Email) VALUES ('Positive Technologies', 'sales@ptsecurity.com');

-- 2. Locations
INSERT INTO Locations (Room_Number, Planned_Growth_Seats) VALUES ('101', 5);
INSERT INTO Locations (Room_Number, Planned_Growth_Seats) VALUES ('102', 3);
INSERT INTO Locations (Room_Number, Planned_Growth_Seats) VALUES ('201', 10);
INSERT INTO Locations (Room_Number, Planned_Growth_Seats) VALUES ('202', 0);
INSERT INTO Locations (Room_Number, Planned_Growth_Seats) VALUES ('203', 8);
INSERT INTO Locations (Room_Number, Planned_Growth_Seats) VALUES ('301', 4);
INSERT INTO Locations (Room_Number, Planned_Growth_Seats) VALUES ('302', 6);
INSERT INTO Locations (Room_Number, Planned_Growth_Seats) VALUES ('401', 0);
INSERT INTO Locations (Room_Number, Planned_Growth_Seats) VALUES ('402', 2);
INSERT INTO Locations (Room_Number, Planned_Growth_Seats) VALUES ('Серверная', 0);


-- 3. Products
INSERT INTO Products (Vendor_ID, Name, Category, Version) VALUES (1, 'Windows 11 Pro',           'Офисное',        '23H2');
INSERT INTO Products (Vendor_ID, Name, Category, Version) VALUES (1, 'Microsoft Office 365',     'Офисное',        '2024');
INSERT INTO Products (Vendor_ID, Name, Category, Version) VALUES (1, 'Visual Studio Professional','Разработка',     '2022');
INSERT INTO Products (Vendor_ID, Name, Category, Version) VALUES (1, 'SQL Server Developer',     'СУБД',           '2022');
INSERT INTO Products (Vendor_ID, Name, Category, Version) VALUES (2, 'Adobe Photoshop',          'Графика',        '2024');
INSERT INTO Products (Vendor_ID, Name, Category, Version) VALUES (2, 'Adobe Illustrator',        'Графика',        '2024');
INSERT INTO Products (Vendor_ID, Name, Category, Version) VALUES (2, 'Adobe Premiere Pro',       'Графика',        '2024');
INSERT INTO Products (Vendor_ID, Name, Category, Version) VALUES (3, 'IntelliJ IDEA Ultimate',   'Разработка',     '2024.1');
INSERT INTO Products (Vendor_ID, Name, Category, Version) VALUES (3, 'PyCharm Professional',     'Разработка',     '2024.1');
INSERT INTO Products (Vendor_ID, Name, Category, Version) VALUES (3, 'DataGrip',                 'СУБД',           '2024.1');
INSERT INTO Products (Vendor_ID, Name, Category, Version) VALUES (4, 'Kaspersky Endpoint Security','Безопасность',  '12.0');
INSERT INTO Products (Vendor_ID, Name, Category, Version) VALUES (4, 'Kaspersky Total Security',  'Безопасность',  '2024');
INSERT INTO Products (Vendor_ID, Name, Category, Version) VALUES (5, '1С:Предприятие',           'Учёт',           '8.3');
INSERT INTO Products (Vendor_ID, Name, Category, Version) VALUES (5, '1С:Бухгалтерия',           'Учёт',           '3.0');
INSERT INTO Products (Vendor_ID, Name, Category, Version) VALUES (6, 'AutoCAD',                  'Проектирование', '2024');
INSERT INTO Products (Vendor_ID, Name, Category, Version) VALUES (6, '3ds Max',                  'Проектирование', '2024');
INSERT INTO Products (Vendor_ID, Name, Category, Version) VALUES (7, 'Oracle Database SE',       'СУБД',           '21c');
INSERT INTO Products (Vendor_ID, Name, Category, Version) VALUES (7, 'Oracle Java SE',           'Разработка',     '21');
INSERT INTO Products (Vendor_ID, Name, Category, Version) VALUES (8, 'MaxPatrol SIEM',           'Безопасность',   '7.0');
INSERT INTO Products (Vendor_ID, Name, Category, Version) VALUES (8, 'PT Application Firewall',  'Безопасность',   '4.0');

-- 4. Licenses
    -- Product 1
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (1, DATE '2024-01-15', DATE '2026-01-15', 12000, 20);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (1, DATE '2024-02-15', DATE '2026-01-15', 12000, 20);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (1, DATE '2024-03-15', DATE '2026-01-15', 12000, 20);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (1, DATE '2024-04-15', DATE '2026-01-15', 12000, 20);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (1, DATE '2024-05-15', DATE '2026-01-15', 12000, 20);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (1, DATE '2024-06-15', DATE '2026-01-15', 12000, 20);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (1, DATE '2024-07-10', DATE '2026-05-10', 12500, 15);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (1, DATE '2024-08-20', DATE '2026-09-20', 13000, 10);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (1, DATE '2024-09-05', DATE '2027-02-05', 13500, 12);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (1, DATE '2024-10-15', DATE '2027-07-15', 14000, 18);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (1, DATE '2024-11-01', DATE '2028-03-01', 14500, 10);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (1, DATE '2024-12-10', DATE '2028-10-10', 15000, 8);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (1, DATE '2025-01-15', DATE '2027-01-15', 15500, 12);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (1, DATE '2025-02-10', DATE '2027-02-10', 15800, 14);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (1, DATE '2025-03-05', DATE '2027-08-05', 16000, 10);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (1, DATE '2025-04-20', DATE '2027-10-20', 16200, 16);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (1, DATE '2025-05-12', DATE '2028-01-12', 16500, 9);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (1, DATE '2025-06-01', DATE '2028-03-01', 16800, 11);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (1, DATE '2025-07-18', DATE '2028-07-18', 17000, 13);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (1, DATE '2025-08-22', DATE '2029-02-22', 17200, 8);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (1, DATE '2025-09-14', DATE '2029-04-14', 17500, 15);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (1, DATE '2025-10-07', DATE '2029-09-07', 17800, 10);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (1, DATE '2025-11-19', DATE '2029-11-19', 18000, 12);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (1, DATE '2025-12-03', DATE '2030-06-03', 18200, 14);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (1, DATE '2026-01-25', DATE '2030-01-25', 18500, 11);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (1, DATE '2026-02-14', DATE '2030-07-14', 18800, 9);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (1, DATE '2026-03-09', DATE '2030-10-09', 19000, 13);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (1, DATE '2026-04-17', DATE '2031-01-17', 19200, 16);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (1, DATE '2026-05-05', DATE '2031-03-05', 19500, 10);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (1, DATE '2026-06-28', DATE '2031-06-28', 19800, 12);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (1, DATE '2026-07-15', DATE '2031-11-15', 20000, 8);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (1, DATE '2026-08-30', DATE '2032-02-28', 20200, 14);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (1, DATE '2026-09-22', DATE '2032-05-22', 20500, 10);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (1, DATE '2026-10-11', DATE '2032-09-11', 20800, 7);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (1, DATE '2026-11-08', DATE '2032-12-08', 21000, 15);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (1, DATE '2026-12-19', DATE '2033-04-19', 21200, 9);
    -- Product 2
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (2, DATE '2024-01-01', DATE '2024-02-01', 5000, 25);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (2, DATE '2024-02-15', DATE '2024-06-15', 5200, 20);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (2, DATE '2024-03-05', DATE '2024-11-05', 5400, 30);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (2, DATE '2024-04-05', DATE '2024-11-05', 6400, 30);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (2, DATE '2024-05-05', DATE '2024-11-05', 7400, 30);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (2, DATE '2024-06-05', DATE '2024-11-05', 3400, 30);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (2, DATE '2024-07-05', DATE '2024-11-05', 5300, 30);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (2, DATE '2024-08-10', DATE '2025-03-10', 5200, 15);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (2, DATE '2024-09-20', DATE '2025-08-20', 5100, 25);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (2, DATE '2024-11-25', DATE '2026-01-25', 6000, 20);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (2, DATE '2024-12-30', DATE '2026-09-30', 6200, 35);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (2, DATE '2025-01-10', DATE '2025-06-10', 6300, 28);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (2, DATE '2025-02-22', DATE '2025-09-22', 6400, 22);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (2, DATE '2025-03-15', DATE '2026-01-15', 6500, 30);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (2, DATE '2025-04-05', DATE '2026-04-05', 6600, 18);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (2, DATE '2025-05-20', DATE '2026-08-20', 6700, 25);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (2, DATE '2025-06-12', DATE '2026-11-12', 6800, 32);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (2, DATE '2025-07-01', DATE '2027-02-01', 6900, 20);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (2, DATE '2025-08-14', DATE '2027-05-14', 7000, 27);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (2, DATE '2025-09-28', DATE '2027-09-28', 7100, 15);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (2, DATE '2025-10-19', DATE '2027-12-19', 7200, 24);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (2, DATE '2025-11-09', DATE '2028-03-09', 7300, 30);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (2, DATE '2025-12-25', DATE '2028-07-25', 7400, 19);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (2, DATE '2026-01-18', DATE '2028-10-18', 7500, 26);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (2, DATE '2026-02-07', DATE '2029-01-07', 7600, 22);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (2, DATE '2026-03-29', DATE '2029-04-29', 7700, 31);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (2, DATE '2026-04-13', DATE '2029-07-13', 7800, 17);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (2, DATE '2026-05-24', DATE '2029-10-24', 7900, 28);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (2, DATE '2026-06-16', DATE '2029-12-16', 8000, 23);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (2, DATE '2026-07-08', DATE '2030-03-08', 8100, 35);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (2, DATE '2026-08-26', DATE '2030-08-26', 8200, 20);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (2, DATE '2026-09-17', DATE '2030-11-17', 8300, 29);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (2, DATE '2026-10-03', DATE '2031-01-03', 8400, 24);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (2, DATE '2026-11-27', DATE '2031-04-27', 8500, 18);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (2, DATE '2026-12-12', DATE '2031-09-12', 8600, 32);
    -- Product 3
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (3, DATE '2024-01-20', DATE '2026-03-20', 45000, 8);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (3, DATE '2024-03-20', DATE '2026-03-20', 45000, 8);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (3, DATE '2024-04-20', DATE '2026-03-20', 45000, 8);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (3, DATE '2024-05-20', DATE '2026-03-20', 45000, 8);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (3, DATE '2024-06-20', DATE '2026-03-20', 45000, 8);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (3, DATE '2024-07-10', DATE '2026-07-10', 46000, 10);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (3, DATE '2024-09-15', DATE '2027-01-15', 47000, 6);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (3, DATE '2024-10-15', DATE '2027-06-15', 48000, 10);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (3, DATE '2024-11-01', DATE '2028-04-01', 50000, 7);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (3, DATE '2025-01-05', DATE '2027-04-05', 51000, 9);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (3, DATE '2025-02-18', DATE '2027-08-18', 52000, 7);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (3, DATE '2025-03-30', DATE '2027-11-30', 53000, 11);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (3, DATE '2025-04-22', DATE '2028-01-22', 54000, 8);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (3, DATE '2025-05-11', DATE '2028-05-11', 55000, 10);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (3, DATE '2025-06-08', DATE '2028-08-08', 56000, 6);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (3, DATE '2025-07-27', DATE '2028-12-27', 57000, 12);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (3, DATE '2025-08-19', DATE '2029-03-19', 58000, 9);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (3, DATE '2025-09-09', DATE '2029-06-09', 59000, 7);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (3, DATE '2025-10-31', DATE '2029-10-31', 60000, 10);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (3, DATE '2025-11-23', DATE '2030-02-23', 61000, 8);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (3, DATE '2025-12-14', DATE '2030-05-14', 62000, 11);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (3, DATE '2026-01-29', DATE '2030-08-29', 63000, 9);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (3, DATE '2026-02-19', DATE '2030-11-19', 64000, 7);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (3, DATE '2026-03-12', DATE '2031-03-12', 65000, 12);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (3, DATE '2026-04-25', DATE '2031-06-25', 66000, 10);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (3, DATE '2026-05-30', DATE '2031-09-30', 67000, 8);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (3, DATE '2026-06-21', DATE '2031-12-21', 68000, 6);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (3, DATE '2026-07-09', DATE '2032-03-09', 69000, 11);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (3, DATE '2026-08-05', DATE '2032-06-05', 70000, 9);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (3, DATE '2026-09-26', DATE '2032-09-26', 71000, 13);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (3, DATE '2026-10-17', DATE '2033-01-17', 72000, 7);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (3, DATE '2026-11-13', DATE '2033-04-13', 73000, 10);
INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats) VALUES (3, DATE '2026-12-01', DATE '2033-07-01', 74000, 8);


INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats)
VALUES (5, DATE '2025-11-15', DATE '2026-11-15', 8200, 12);

INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats)
VALUES (5, DATE '2026-02-10', DATE '2027-02-10', 8500, 10);

INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats)
VALUES (8, DATE '2025-12-05', DATE '2026-12-05', 15000, 7);

INSERT INTO Licenses (Product_ID, Purchase_Date, Expiration_Date, Unit_Price, Total_Seats)
VALUES (8, DATE '2026-03-18', DATE '2027-03-18', 15800, 9);


-- 5. Devices
INSERT INTO Devices (Location_ID, Device_Type, Purchase_Date, Service_Life_Months, Hostname) VALUES (1, 'ПК',      DATE '2022-09-01', 60, 'PC-101-01');
INSERT INTO Devices (Location_ID, Device_Type, Purchase_Date, Service_Life_Months, Hostname) VALUES (1, 'ПК',      DATE '2022-09-01', 60, 'PC-101-02');
INSERT INTO Devices (Location_ID, Device_Type, Purchase_Date, Service_Life_Months, Hostname) VALUES (1, 'ПК',      DATE '2022-09-01', 60, 'PC-101-03');
INSERT INTO Devices (Location_ID, Device_Type, Purchase_Date, Service_Life_Months, Hostname) VALUES (1, 'ПК',      DATE '2023-09-01', 60, 'PC-101-04');
INSERT INTO Devices (Location_ID, Device_Type, Purchase_Date, Service_Life_Months, Hostname) VALUES (1, 'ПК',      DATE '2023-09-01', 60, 'PC-101-05');
INSERT INTO Devices (Location_ID, Device_Type, Purchase_Date, Service_Life_Months, Hostname) VALUES (2, 'ПК',      DATE '2023-01-15', 60, 'PC-102-01');
INSERT INTO Devices (Location_ID, Device_Type, Purchase_Date, Service_Life_Months, Hostname) VALUES (2, 'ПК',      DATE '2023-01-15', 60, 'PC-102-02');
INSERT INTO Devices (Location_ID, Device_Type, Purchase_Date, Service_Life_Months, Hostname) VALUES (2, 'ПК',      DATE '2023-01-15', 60, 'PC-102-03');
INSERT INTO Devices (Location_ID, Device_Type, Purchase_Date, Service_Life_Months, Hostname) VALUES (3, 'ПК',      DATE '2021-09-01', 60, 'PC-201-01');
INSERT INTO Devices (Location_ID, Device_Type, Purchase_Date, Service_Life_Months, Hostname) VALUES (3, 'ПК',      DATE '2021-09-01', 60, 'PC-201-02');
INSERT INTO Devices (Location_ID, Device_Type, Purchase_Date, Service_Life_Months, Hostname) VALUES (3, 'ПК',      DATE '2021-09-01', 60, 'PC-201-03');
INSERT INTO Devices (Location_ID, Device_Type, Purchase_Date, Service_Life_Months, Hostname) VALUES (3, 'ПК',      DATE '2023-03-01', 60, 'PC-201-04');
INSERT INTO Devices (Location_ID, Device_Type, Purchase_Date, Service_Life_Months, Hostname) VALUES (3, 'ПК',      DATE '2023-03-01', 60, 'PC-201-05');
INSERT INTO Devices (Location_ID, Device_Type, Purchase_Date, Service_Life_Months, Hostname) VALUES (4, 'Ноутбук', DATE '2023-06-01', 48, 'NB-202-01');
INSERT INTO Devices (Location_ID, Device_Type, Purchase_Date, Service_Life_Months, Hostname) VALUES (4, 'Ноутбук', DATE '2023-06-01', 48, 'NB-202-02');
INSERT INTO Devices (Location_ID, Device_Type, Purchase_Date, Service_Life_Months, Hostname) VALUES (4, 'Ноутбук', DATE '2024-01-10', 48, 'NB-202-03');
INSERT INTO Devices (Location_ID, Device_Type, Purchase_Date, Service_Life_Months, Hostname) VALUES (5, 'ПК',      DATE '2022-01-15', 60, 'PC-203-01');
INSERT INTO Devices (Location_ID, Device_Type, Purchase_Date, Service_Life_Months, Hostname) VALUES (5, 'ПК',      DATE '2022-01-15', 60, 'PC-203-02');
INSERT INTO Devices (Location_ID, Device_Type, Purchase_Date, Service_Life_Months, Hostname) VALUES (5, 'ПК',      DATE '2024-02-01', 60, 'PC-203-03');
INSERT INTO Devices (Location_ID, Device_Type, Purchase_Date, Service_Life_Months, Hostname) VALUES (5, 'ПК',      DATE '2024-02-01', 60, 'PC-203-04');
INSERT INTO Devices (Location_ID, Device_Type, Purchase_Date, Service_Life_Months, Hostname) VALUES (6, 'ПК',      DATE '2023-09-01', 60, 'PC-301-01');
INSERT INTO Devices (Location_ID, Device_Type, Purchase_Date, Service_Life_Months, Hostname) VALUES (6, 'ПК',      DATE '2023-09-01', 60, 'PC-301-02');
INSERT INTO Devices (Location_ID, Device_Type, Purchase_Date, Service_Life_Months, Hostname) VALUES (6, 'ПК',      DATE '2024-09-01', 60, 'PC-301-03');
INSERT INTO Devices (Location_ID, Device_Type, Purchase_Date, Service_Life_Months, Hostname) VALUES (7, 'Ноутбук', DATE '2024-03-01', 48, 'NB-302-01');
INSERT INTO Devices (Location_ID, Device_Type, Purchase_Date, Service_Life_Months, Hostname) VALUES (7, 'Ноутбук', DATE '2024-03-01', 48, 'NB-302-02');
INSERT INTO Devices (Location_ID, Device_Type, Purchase_Date, Service_Life_Months, Hostname) VALUES (10, 'Сервер', DATE '2021-06-01', 84, 'SRV-01');
INSERT INTO Devices (Location_ID, Device_Type, Purchase_Date, Service_Life_Months, Hostname) VALUES (10, 'Сервер', DATE '2022-12-01', 84, 'SRV-02');
INSERT INTO Devices (Location_ID, Device_Type, Purchase_Date, Service_Life_Months, Hostname) VALUES (10, 'Сервер', DATE '2024-06-01', 84, 'SRV-03');

-- 6. Installations
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (1,  1, DATE '2025-03-28', 450);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (2,  1, DATE '2025-03-27', 430);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (3,  1, DATE '2025-03-28', 410);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (4,  2, DATE '2025-03-26', 380);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (5,  2, DATE '2025-03-28', 395);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (6,  1, DATE '2025-03-25', 350);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (7,  1, DATE '2025-03-28', 360);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (8,  1, DATE '2025-03-27', 340);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (1,  4, DATE '2025-03-28', 500);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (2,  4, DATE '2025-03-27', 480);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (3,  4, DATE '2025-03-28', 490);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (6,  5, DATE '2025-03-25', 310);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (7,  5, DATE '2025-03-28', 320);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (9,  5, DATE '2025-03-20', 280);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (10, 5, DATE '2025-03-22', 260);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (9,  7, DATE '2025-03-15', 120);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (10, 7, DATE '2025-03-18', 140);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (11, 7, DATE '2025-03-20', 110);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (12, 8, DATE '2025-03-25', 95);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (13, 8, DATE '2025-03-28', 105);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (17, 10, DATE '2025-03-22', 85);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (18, 11, DATE '2025-03-28', 92);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (19, 11, DATE '2025-03-27', 78);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (20, 12, DATE '2025-02-10', 45);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (17, 13, DATE '2025-03-20', 60);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (18, 14, DATE '2025-03-25', 72);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (19, 14, DATE '2025-03-28', 55);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (14, 15, DATE '2025-03-18', 30);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (15, 16, DATE '2025-03-28', 42);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (9,  17, DATE '2025-03-10', 200);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (10, 17, DATE '2025-03-15', 190);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (11, 18, DATE '2025-03-28', 175);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (12, 18, DATE '2025-03-26', 160);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (21, 19, DATE '2025-03-12', 140);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (22, 20, DATE '2025-03-28', 155);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (23, 20, DATE '2025-03-25', 130);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (24, 21, DATE '2025-03-20', 60);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (25, 21, DATE '2025-03-28', 55);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (1,  22, DATE '2025-03-28', 500);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (2,  22, DATE '2025-03-28', 490);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (3,  22, DATE '2025-03-28', 480);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (6,  23, DATE '2025-03-28', 470);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (7,  23, DATE '2025-03-28', 460);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (9,  23, DATE '2025-03-28', 440);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (10, 23, DATE '2025-03-28', 430);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (11, 24, DATE '2025-03-28', 200);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (17, 24, DATE '2025-03-28', 210);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (14, 25, DATE '2025-03-28', 300);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (15, 25, DATE '2025-03-28', 290);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (16, 26, DATE '2025-03-28', 150);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (21, 27, DATE '2025-03-20', 250);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (22, 27, DATE '2025-03-22', 240);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (23, 28, DATE '2025-03-18', 180);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (17, 29, DATE '2025-03-15', 70);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (18, 30, DATE '2025-03-28', 85);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (19, 30, DATE '2025-03-25', 65);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (20, 30, DATE '2025-03-20', 50);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (26, 9, DATE '2025-03-28', 1000);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (27, 9, DATE '2025-03-28', 950);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (28, 33, DATE '2025-03-28', 800);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (26, 34, DATE '2025-03-28', 600);
INSERT INTO Installations (Device_ID, License_ID, Last_Activity_Date, Usage_Count) VALUES (27, 35, DATE '2025-03-28', 550);

-- 7. Requests
INSERT INTO Requests (Product_ID, User_Name, User_Email, Request_Date, Status) VALUES (2, 'Иванов А.С.', 'ivanov@univ.ru', DATE '2024-09-01', 'Одобрено');
INSERT INTO Requests (Product_ID, User_Name, User_Email, Request_Date, Status) VALUES (2, 'Иванов А.С.', 'ivanov@univ.ru', DATE '2024-09-01', 'Одобрено');
INSERT INTO Requests (Product_ID, User_Name, User_Email, Request_Date, Status) VALUES (5, 'Сидоров К.Л.', 'sidorov@univ.ru', DATE '2024-09-10', 'Одобрено');
INSERT INTO Requests (Product_ID, User_Name, User_Email, Request_Date, Status) VALUES (5, 'Сидоров К.Л.', 'sidorov@univ.ru', DATE '2024-09-10', 'Одобрено');
INSERT INTO Requests (Product_ID, User_Name, User_Email, Request_Date, Status) VALUES (3, 'Петрова М.В.', 'petrova@univ.ru', DATE '2024-09-05', 'Одобрено');
INSERT INTO Requests (Product_ID, User_Name, User_Email, Request_Date, Status) VALUES (3, 'Петрова М.В.', 'petrova@univ.ru', DATE '2024-09-05', 'Одобрено');
INSERT INTO Requests (Product_ID, User_Name, User_Email, Request_Date, Status) VALUES (8,  'Козлов Д.А.',    'kozlov@univ.ru',    DATE '2024-09-15', 'Одобрено');
INSERT INTO Requests (Product_ID, User_Name, User_Email, Request_Date, Status) VALUES (15, 'Морозова Е.И.',  'morozova@univ.ru',  DATE '2024-10-01', 'Одобрено');
INSERT INTO Requests (Product_ID, User_Name, User_Email, Request_Date, Status) VALUES (9,  'Волков Р.С.',    'volkov@univ.ru',    DATE '2024-10-10', 'Одобрено');
INSERT INTO Requests (Product_ID, User_Name, User_Email, Request_Date, Status) VALUES (6,  'Новикова А.П.',  'novikova@univ.ru',  DATE '2024-10-15', 'Одобрено');
INSERT INTO Requests (Product_ID, User_Name, User_Email, Request_Date, Status) VALUES (7,  'Фёдоров И.М.',   'fedorov@univ.ru',   DATE '2024-11-01', 'Одобрено');
INSERT INTO Requests (Product_ID, User_Name, User_Email, Request_Date, Status) VALUES (16, 'Алексеева Т.Н.', 'alekseeva@univ.ru', DATE '2024-11-10', 'Отклонено');
INSERT INTO Requests (Product_ID, User_Name, User_Email, Request_Date, Status) VALUES (10, 'Егоров В.В.',    'egorov@univ.ru',    DATE '2024-11-20', 'Одобрено');
INSERT INTO Requests (Product_ID, User_Name, User_Email, Request_Date, Status) VALUES (13, 'Дмитриева О.С.', 'dmitrieva@univ.ru', DATE '2024-12-01', 'Одобрено');
INSERT INTO Requests (Product_ID, User_Name, User_Email, Request_Date, Status) VALUES (2,  'Кузнецов П.А.',  'kuznetsov@univ.ru', DATE '2024-12-05', 'В ожидании');
INSERT INTO Requests (Product_ID, User_Name, User_Email, Request_Date, Status) VALUES (5,  'Попова Л.Г.',    'popova@univ.ru',    DATE '2024-12-10', 'В ожидании');
INSERT INTO Requests (Product_ID, User_Name, User_Email, Request_Date, Status) VALUES (3,  'Соколов А.Р.',   'sokolov@univ.ru',   DATE '2025-01-10', 'Одобрено');
INSERT INTO Requests (Product_ID, User_Name, User_Email, Request_Date, Status) VALUES (11, 'Лебедева Н.К.',  'lebedeva@univ.ru',  DATE '2025-01-15', 'Одобрено');
INSERT INTO Requests (Product_ID, User_Name, User_Email, Request_Date, Status) VALUES (15, 'Михайлов С.Д.',  'mikhailov@univ.ru', DATE '2025-01-20', 'В ожидании');
INSERT INTO Requests (Product_ID, User_Name, User_Email, Request_Date, Status) VALUES (8,  'Новиков Е.А.',   'novikov@univ.ru',   DATE '2025-02-01', 'Одобрено');
INSERT INTO Requests (Product_ID, User_Name, User_Email, Request_Date, Status) VALUES (19, 'Зайцев О.П.',    'zaytsev@univ.ru',   DATE '2025-02-05', 'Отклонено');
INSERT INTO Requests (Product_ID, User_Name, User_Email, Request_Date, Status) VALUES (20, 'Борисова Д.Л.',  'borisova@univ.ru',  DATE '2025-02-10', 'Отклонено');
INSERT INTO Requests (Product_ID, User_Name, User_Email, Request_Date, Status) VALUES (2,  'Григорьев К.М.', 'grigoriev@univ.ru', DATE '2025-02-15', 'Одобрено');
INSERT INTO Requests (Product_ID, User_Name, User_Email, Request_Date, Status) VALUES (9,  'Романова В.И.',  'romanova@univ.ru',  DATE '2025-02-20', 'В ожидании');
INSERT INTO Requests (Product_ID, User_Name, User_Email, Request_Date, Status) VALUES (14, 'Васильев Н.С.',  'vasiliev@univ.ru',  DATE '2025-03-01', 'Одобрено');
INSERT INTO Requests (Product_ID, User_Name, User_Email, Request_Date, Status) VALUES (1,  'Павлова А.М.',   'pavlova@univ.ru',   DATE '2025-03-05', 'В ожидании');
INSERT INTO Requests (Product_ID, User_Name, User_Email, Request_Date, Status) VALUES (17, 'Семёнов Д.В.',   'semenov@univ.ru',   DATE '2025-03-10', 'Отклонено');
INSERT INTO Requests (Product_ID, User_Name, User_Email, Request_Date, Status) VALUES (4,  'Голубева И.Р.',  'golubeva@univ.ru',  DATE '2025-03-15', 'Одобрено');

COMMIT;

-- Проверка загрузки
SELECT * FROM Requests;
SELECT * FROM Installations;
SELECT * FROM Devices;
SELECT * FROM Licenses;
SELECT * FROM Products;
SELECT * FROM Locations;
SELECT * FROM Vendors;

-- 3
-- Вычисление итогов стоимости определенного вида ПО
-- помесячно, за квартал, за полгода, за год
-- Одним запросом, без процедуры
WITH src AS (
    SELECT
        p.Name AS ProductName,
        EXTRACT(YEAR FROM l.Purchase_Date) AS Yr,
        EXTRACT(MONTH FROM l.Purchase_Date) AS Mn,
        TO_NUMBER(TO_CHAR(l.Purchase_Date, 'Q')) AS Qr,
        CASE
            WHEN EXTRACT(MONTH FROM l.Purchase_Date) <= 6 THEN 1
            ELSE 2
        END AS Hf,
        l.Total_Seats AS TotalSeats,
        l.Unit_Price AS UnitPrice
    FROM Licenses l
    JOIN Products p
        ON p.Product_ID = l.Product_ID
    WHERE l.Product_ID = 2
      AND l.Purchase_Date BETWEEN DATE '2023-01-01' AND DATE '2025-12-31'
)
SELECT
    ProductName,
    Yr AS Year,
    CASE WHEN GROUPING(Mn) = 0 THEN Mn END AS Month,
    CASE WHEN GROUPING(Qr) = 0 THEN Qr END AS Quarter,
    CASE WHEN GROUPING(Hf) = 0 THEN Hf END AS HalfYear,
    SUM(TotalSeats) AS TotalLicenses,
    SUM(TotalSeats * UnitPrice) AS TotalCost
FROM src
GROUP BY GROUPING SETS (
    (ProductName, Yr, Mn),
    (ProductName, Yr, Qr),
    (ProductName, Yr, Hf),
    (ProductName, Yr)
)
ORDER BY Year, Month, Quarter, HalfYear;

-- Задание 4
-- Вычисление итогов стоимости ПО за период:
-- - количество и стоимость лицензий
-- - сравнение с общим количеством лицензий, %
-- - сравнение с общей стоимостью лицензий, %
-- Одним запросом, без процедуры

SELECT
    p.Category AS Category,
    p.Name AS Product,
    EXTRACT(YEAR FROM l.Purchase_Date) AS Yr,
    COUNT(*) AS Lic_Count,
    SUM(l.Unit_Price * l.Total_Seats) AS Total_Cost,
    CAST( COUNT(*) * 100 / SUM(COUNT(*)) OVER ()AS NUMBER(5,2)) AS Pct_Of_Count,
    CAST( SUM(l.Unit_Price * l.Total_Seats) * 100 /
        SUM(SUM(l.Unit_Price * l.Total_Seats)) OVER ()  AS NUMBER(5,2)
            ) AS Pct_Of_Cost

FROM Licenses l
JOIN Products p ON l.Product_ID = p.Product_ID
WHERE l.Purchase_Date BETWEEN DATE '2024-01-01' AND DATE '2026-12-31'
GROUP BY p.Category, p.Name, EXTRACT(YEAR FROM l.Purchase_Date)
ORDER BY p.Category, p.Name, Yr;

-- Задание 7
-- Для каждого вендора - суммы затрат
-- на лицензирование за последние 6 месяцев помесячно

SELECT
    v.Name AS "Вендор",
    EXTRACT(YEAR FROM l.Purchase_Date) AS "Год",
    EXTRACT(MONTH FROM l.Purchase_Date) AS "Месяц",
    SUM(l.Unit_Price * l.Total_Seats) AS "Стоимость за месяц",
    SUM(SUM(l.Unit_Price * l.Total_Seats)) OVER (
        PARTITION BY v.Vendor_ID
    ) AS "Итого за 6 месяцев по вендору"
FROM Licenses l
JOIN Products p
    ON l.Product_ID = p.Product_ID
JOIN Vendors v
    ON p.Vendor_ID = v.Vendor_ID
WHERE l.Purchase_Date >= ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -5)
  AND l.Purchase_Date <  ADD_MONTHS(TRUNC(SYSDATE, 'MM'), 1)
GROUP BY
    v.Vendor_ID,
    v.Name,
    EXTRACT(YEAR FROM l.Purchase_Date),
    EXTRACT(MONTH FROM l.Purchase_Date)
ORDER BY
    v.Name,
    "Год",
    "Месяц";

-- Задание 8
-- Какой тип ПО (категория) использовался
-- наибольшее число раз для устройств определённого вида
-- Одним запросом, без процедуры
WITH cte AS (
    SELECT
    d.Device_Type AS Device_Type,
    p.Category AS Category,
    COUNT(*) AS Install_Count,
    ROW_NUMBER() OVER (
        PARTITION BY d.Device_Type
        ORDER BY COUNT(*) DESC
    ) AS rn
FROM Installations i
    JOIN Devices  d ON i.Device_ID  = d.Device_ID
    JOIN Licenses l ON i.License_ID = l.License_ID
    JOIN Products p ON l.Product_ID = p.Product_ID
GROUP BY d.Device_Type, p.Category
)

SELECT Device_Type, Category, Install_Count
FROM cte
WHERE rn = 1;
